Testing workflows
oven-sh/bun pull request #10157
Opened 2024-04-10 22:48 UTC by Electroid

### What does this PR do?

Do not merge. Work in progress.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?

2024-04-15 22:45 UTC, paperdave requested changes
i really love how this is coming together.

2024-04-15 22:45 UTC, paperdave commented on packages/bun-internal-test/src/runner.node.mjs
> +  break; // HACK
this isnt intentional for final i assume

2024-04-15 22:45 UTC, paperdave commented on .github/workflows/build-windows.yml
> +        type: boolean
is there a reason this cannot be named `optimize` and be a string? with the default being ReleaseFast?

2024-04-17 01:35 UTC, paperclover approved these changes

2024-04-17 02:29 UTC, Jarred-Sumner commented on .github/workflows/build-darwin.yml
> +          HOMEBREW_NO_INSTALL_CLEANUP: 1
we should add that 4th arg

2024-04-17 02:34 UTC, Jarred-Sumner commented on .github/workflows/upload.yml
> +        uses: shallwefootball/s3-upload-action@4350529f410221787ccf424e50133cbc1b52704e
I don't love relying on this random github action that hasn't been updated in a year https://github.com/shallwefootball/upload-s3-action

2024-04-17 02:35 UTC, Jarred-Sumner commented on .github/workflows/run-test.yml
> +          node packages/bun-internal-test/src/runner.node.mjs
```suggestion
          node packages/bun-internal-test/src/runner.node.mjs || true
```

2024-04-17 02:39 UTC, merged