Fix issue #10376
oven-sh/bun pull request #10421
Opened 2024-04-21 18:01 UTC by Uziniii

### What does this PR do?

This pr avoid infinite install loop when putting bun install in post install script in package.json by exiting

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

- [ ] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I included a test for the new code, or an existing test covers it
- [ ] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed
- [x] I wrote TypeScript/JavaScript tests and they pass locally (`bun-debug test test-file-name.test`)

2024-04-22 20:42 UTC, paperdave requested changes
- please use `bun.strings.eqlComptime()`. you can do this all inline like `if (bun.strings.eqlComptime(combined_script, "bun install")) {`
- i don't think `bun-debug` needs to be considered here
- it should print an error message as to why this is going to be a recursive call. use `Output.errGeneric(fmt, args)` and/or `Output.note` for this.

2024-04-23 21:34 UTC, paperdave requested changes

2024-04-23 21:34 UTC, paperdave commented on src/install/lifecycle_script_runner.zig
> +        if (combined_script.len >= install_script.len and bun.strings.eqlComptime(combined_script[0..install_script.len], install_script)) {
i didnt realize this was a starts with check before. it can just be `bun.strings.hasPrefixComptime(combined_script, "bun install")`

2024-04-23 21:34 UTC, paperdave commented on src/install/lifecycle_script_runner.zig
> +            Output.errGeneric("post install script has been canceled to prevent an infinite loop", .{});
```suggestion
            Output.errGeneric("\"{s}\" package.json script calling \"bun install\" causes an infinite loop.", .{this.scriptName()});
            
```

2024-04-23 21:34 UTC, paperdave commented on src/install/lifecycle_script_runner.zig
> +            Global.exit(0);
```suggestion
            Global.exit(1);
```

2024-04-25 02:11 UTC, dylan-conway approved these changes
Going to merge this. I don't think this is perfect solution (scripts could be `foo=bun; $foo i`, `bun add ...`, ...), but `bun install` will cover most situations. If we had the bun shell enabled for lifecycle scripts on all platforms, we could probably detect `bun install/add` inside the interpreter accurately

2024-04-25 02:12 UTC, merged

2024-04-25 03:27 UTC, dylan-conway commented
Needed to revert this pr. It's not uncommon for projects to have `postinstall: "bun install --cwd <dir>"`. This won't trigger an  infinite loop because \<dir\> is not a workspace