test: use resource disposal to ensure servers shutdown even if tests fail
oven-sh/bun pull request #11106
Opened 2024-05-16 04:44 UTC by nektro

`expect()` throws if given a non-passing value so many tests forget to cleanup or are wrapped in `try`/`finally`. with `using` they don't have to.

2024-05-16 05:45 UTC, Jarred-Sumner requested changes
The tests which start a server inside a `beforeAll` / `afterAll` need to continue doing that

It's really easy to use all the CI machine's open ports and then cause other tests to fail

2024-05-16 22:53 UTC, nektro commented
doing it this way still only creates one server per test but also has the added benefit that once we run tests in parallel they wont clobber the same global variable

2024-05-17 00:17 UTC, Jarred-Sumner commented on test/js/web/fetch/fetch.test.ts
> -  var server: Server;
can we bring this back

2024-05-17 00:26 UTC, merged

2024-05-17 00:26 UTC, Jarred-Sumner commented
Thank you