More Worker Fixes
oven-sh/bun pull request #11619
Opened 2024-06-05 07:23 UTC by Jarred-Sumner

### What does this PR do?

- Prevent calling into JavaScript in `atexit` handlers 
- Add some tests for worker destruction in fetch
- Fix bug where we may unnecessarily enter the event loop to handle `beforeExit` when `beforeExit` was never listened to

### How did you verify your code works?

2024-06-05 19:16 UTC, cirospaciari requested changes

2024-06-05 19:16 UTC, cirospaciari commented on src/bun.js/webcore/response.zig
> +                        this.ignoreRemainingResponseBody();
we should add `scenario 4 here`, resolving the promise when `vm.isShuttingDown() == true` is ok? because we would be touching JS again in that case, if is not we should add this verification at the top

2024-06-05 19:16 UTC, cirospaciari commented on test/js/node/worker_threads/worker_thread_check.ts
> +      await fetch("http://localhost:" + port);
we should add cases using `fetch(url).then(res=> res.arrayBuffer())` so we know that closes clean if we are waiting some promise/buffering in the fetch

2024-06-05 23:35 UTC, paperdave commented on src/bun.js/javascript.zig
> +    extern fn Process__dispatchOnBeforeExit(*JSC.JSGlobalObject, code: u8) c_int;
note: int32_t in c++ is not zig c_int

2024-06-06 10:44 UTC, Jarred-Sumner commented on test/js/node/worker_threads/worker_thread_check.ts
> +      await resp.blob();
```suggestion
      resp.blob();
```

2024-06-06 10:44 UTC, Jarred-Sumner commented on test/js/node/worker_threads/worker_thread_check.ts
> +      await Bun.file(import.meta.path).text();
```suggestion
      Bun.file(import.meta.path).text();
```

2025-03-08 04:13 UTC, closed without merging