shell: Fix memory leak, lazily create `ShellInterpreter` object
oven-sh/bun pull request #11830
Opened 2024-06-13 02:07 UTC by zackradisic

### What does this PR do?

Fixes #11816

**Problem**
- ShellPromise's `resolve/reject` functions closes over `ShellInterpreter` class
- the `ShellInterpreter` class holds strong references to `resolve/reject` functions
- this makes it possible for the `ShellInterpreter` class to never be deinitialized
- was not caught in shell leak tests because of immediately immediately invoked function syntax: `(async function() { /* shell stuff */ })()`

**Fix**
- lazily create `ShellInterpreter` when the `ShellPromise` is actually awaited
- instead of giving `resolve/reject` to `ShellInterpreter`, give it to new `ParsedShellScript` class which holds script AST and other options
- this breaks cycle: now `resolve/reject` don't refer to `ShellInterpreter`
- put `values: ["resolve", "reject"]` in the `ShellInterpreter` class generator
- give `ShellInterpreter` `resolve/reject` when it gets created

2024-06-13 04:12 UTC, Jarred-Sumner commented on src/shell/interpreter.zig
> +    pub fn init(allocator: Allocator) *ShellArgs {
```zig
arena: *bun.ArenaAllocator,

pub usingnamespace bun.New(@This());

pub fn allocator(this: *ShellArgs) std.mem.Allocator {
  return this.arena.allocator();
}

pub fn deinit(this: *ShellArgs) void {
  this.arena.deinit();
  this.destroy();
}

pub fn init() *ShellArgs {
  const arena = bun.new(bun.ArenaAllocator);
  arena.* = bun.ArenaAllocator.init(bun.default_allocator);
  return ShellArgs.new(.{
    .arena = arena,
   });
});
```

2024-06-13 22:40 UTC, Jarred-Sumner requested changes
Test failures

2024-06-14 22:00 UTC, Zamion101 commented
Looks like some tests are failing but they're not associated with this PR. Is it possible to get a Canary for this PR or must all the fails be adressed before it's possible.

2024-06-15 00:20 UTC, Jarred-Sumner commented
@zackradisic bunshell tests are failing on Windows. I think that is a blocker here.

2024-06-15 09:16 UTC, Jarred-Sumner commented on src/shell/interpreter.zig
> +        this.destroy();
This leaks the bun.ArenaAllocator pointer.


```suggestion
        bun.destroy(this.__arena);
        this.destroy();
```

2024-06-17 22:20 UTC, Jarred-Sumner commented on src/shell/interpreter.zig
> +            globalThis.throw("shell: expected 2 arguments, got 0", .{});
Memory leak:

```suggestion
            globalThis.throw("shell: expected 2 arguments, got 0", .{});
            shargs.deinit();
```

2024-06-17 22:23 UTC, Jarred-Sumner commented on src/shell/interpreter.zig
> +        var arguments = JSC.Node.ArgumentsSlice.init(globalThis.bunVM(), arguments_.slice());
This leaks memory on errors.

Let's just not use ArgumentsSlice here - it's unnecessary. And, let's create the shell args after validating the arguments. 

```suggestion
        const arguments = arguments_.slice();
        
       if (arguments.len < 2) {
            globalThis.throwNotEnoughArguments("Bun.$", 2, arguments.len);
            return .zero;
        }
        if (arguments
        const string_args = arguments[0];
        const template_args_jst = arguments[1];
```

2024-06-17 22:26 UTC, Jarred-Sumner commented on src/shell/interpreter.zig
> +        parsed_shell_script.take(
What verifies that the shell args in `parsed_shell_scripts` is not null? If it was null, wouldn't this be undefined memory and cause a segfault?

2024-06-17 22:30 UTC, Jarred-Sumner commented on src/bun.js/api/ShellArgs.classes.ts
> +    JSType: "0b11101110",
```suggestion

```

2024-06-17 22:30 UTC, Jarred-Sumner commented on src/bun.js/api/Shell.classes.ts
>      JSType: "0b11101110",
```suggestion

```

2024-06-18 03:08 UTC, merged