.npmrc follow up
oven-sh/bun pull request #12390
Opened 2024-07-06 06:47 UTC by zackradisic

### What does this PR do?

Fixes #12332
Fixes #12338

Fix unresolved comments from previous PR

2024-07-06 09:09 UTC, Jarred-Sumner commented on src/ini.zig
> +                std.debug.print("{s} = {s}\n", .{ @tagName(this.optname), slice[0..result.count] });
It's a little suspicious that there were no test failures because of this std.debug.print

2024-07-08 18:55 UTC, dylan-conway commented on src/ini.zig
> +    defer allocator.free(source.contents);
This will free contents before it's used by logger. Maybe move `printForLogLevel` to the bottom of this function?

2024-07-08 18:57 UTC, dylan-conway commented on src/ini.zig
> +    var decoded = allocator.alloc(u8, decode_len) catch bun.outOfMemory();
nit
```suggestion
    const decoded = allocator.alloc(u8, decode_len) catch bun.outOfMemory();
```

2024-07-08 21:30 UTC, dylan-conway commented on src/ini.zig
> +    const result = bun.base64.decode(decoded[0..], conf_item.value);
This base64 decode will always fail for `username:password` because it includes invalid character `:`. Will need to change this to find `colon_idx` first

2024-07-08 21:35 UTC, dylan-conway requested changes
Left a few comments. Main things are:
- split `username:password` so `:` isn't decoded
- free source contents after error printing

2024-07-10 03:14 UTC, zackradisic commented on src/ini.zig
> +    const result = bun.base64.decode(decoded[0..], conf_item.value);
this is okay because its the entire string encoded in base64 (e.g. `btoa(username + ":" + password)`)

2024-07-10 05:34 UTC, dylan-conway commented on src/ini.zig
> +    const result = bun.base64.decode(decoded[0..], conf_item.value);
ah right, that makes sense

2024-07-10 05:47 UTC, dylan-conway approved these changes

2024-07-10 06:28 UTC, dylan-conway commented
@zackradisic The test failure on windows in `bun-install-registry.test.ts` is real

2024-07-11 02:35 UTC, merged