fixes relationship between process.kill and process._kill
oven-sh/bun pull request #12792
Opened 2024-07-25 02:15 UTC by nektro

- kill should call _kill
- throw should happen in kill not _kill
- on success kill should return true

for most this change will be invisible but it allows kill to be overridden in the way that the node apis expect
i should add a test before merge

split off from https://github.com/oven-sh/bun/pull/11492 to merge independently

test results should be identical to baseline

2024-07-25 02:22 UTC, Jarred-Sumner commented
Sounds like process.kill() should be implemented in JS

2024-07-25 07:40 UTC, Jarred-Sumner commented
Since `kill` calls `_kill`, `kill` should be in JS or `kill` should be a property on the ProcessObject and we check if the kill WriteBarrier is set and go from JS instead of native.

2024-07-25 07:41 UTC, Jarred-Sumner requested changes
Since `kill` calls `_kill`, `kill` should be in JS or `kill` should be a property on the ProcessObject and we check if the kill WriteBarrier is set and go from JS instead of native.

2024-07-25 22:53 UTC, nektro commented
`process.kill` also accepts a string signal name and needs to call `loadSignalNumberMap()` etc. `process._kill` being replaced is an accepted use case and the function as-is in this patch already checks for exceptions

2024-07-26 01:37 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +    JSValue _killFn = global->processObject()->get(globalObject, Identifier::fromString(vm, "_kill"_s));
```suggestion
    JSValue _killFn = global->processObject()->get(globalObject, Identifier::fromString(vm, "_kill"_s));
    RETURN_IF_EXCEPTION(scope, {});
```

2024-07-26 01:46 UTC, merged