feat: `bun build --compile --sourcemap`
oven-sh/bun pull request #13047
Opened 2024-08-03 08:11 UTC by paperdave

Fixes #12804 

Seems we had advertised this as working on the docs, but the code was never fully wired up.

Though, instead of storing JSON into the final binary, a custom binary format is used to avoid having to decode string literals at runtime. This makes the bundling process take a minuscule amount of extra time, but is worth it considering there is nearly zero sourcemap decoding step (the main step is to just allocate and fill the `ParsedSourceMap`, all the data is ready).

Before merging, I think this needs some more tests, and some more internal doc-comments are needed.

Also, I deleted Lock.init in favor of `.{}`

2024-08-03 08:11 UTC, robobun commented
@paperdave, your commit c3096f8f76e50205289bea59d367fae35a8901d5 is building: [`#1258`](https://buildkite.com/bun/bun/builds/1258)
<!-- generated-comment id=oven-sh/bun#13047 -->

2024-08-05 22:43 UTC, Jarred-Sumner requested changes
Can we use StringPointer instead of making up another type for pointing to a string from a buffer?

Can we make all this `align(1)` so we don't worry about under-aligning things?

2024-08-05 22:59 UTC, paperdave commented
> Can we make all this align(1) so we don't worry about under-aligning things?

We can do this for String Pointer but if we do this for the multi-array-list payload, it would not be valid for the pointer in `MultiArrayList(Mapping)` as it must be `align(@alignOf(Mapping))`. This is why I am careful with alignment in this PR, as not having it aligned would require the data to be cloned into an aligned portion of memory.

When memory is assumed to be aligned when it is not, Bun will crash. It is not hard to align data.

2024-08-06 05:09 UTC, Jarred-Sumner commented on src/sourcemap/sourcemap.zig
> +                return bun.String.createUTF8(bun.path.joinAbs("/", .auto, name));
looks suspicious for Windows

2024-08-06 05:10 UTC, Jarred-Sumner commented on src/StandaloneModuleGraph.zig
> +                string_builder.ensureNextAligned(@alignOf(u32));
can we zero the whole thing instead of zeroing it 4 bytes at a time?

2024-08-06 05:12 UTC, Jarred-Sumner commented on src/StandaloneModuleGraph.zig
> +                var bytes = string_builder.allocatedSlice()[string_builder.len..];
can you use the string builder instead of doing this? this is technical debt

2024-08-06 05:18 UTC, Jarred-Sumner commented on src/StandaloneModuleGraph.zig
> +            const utf16_decode = try bun.js_lexer.decodeStringLiteralEscapeSequencesToUTF16(item.data.e_string.string(arena) catch bun.outOfMemory(), arena);
this should be a method on E.String

like

.decodedUTF8(allocator)

2024-08-06 05:18 UTC, Jarred-Sumner commented on src/StandaloneModuleGraph.zig
> +            const utf16_decode = try bun.js_lexer.decodeStringLiteralEscapeSequencesToUTF16(item.data.e_string.string(arena) catch bun.outOfMemory(), arena);
ditto

2024-08-06 06:17 UTC, Jarred-Sumner commented on src/StandaloneModuleGraph.zig
> +                    return "";
This should return null so that the parent is aware the source map contents was null instead of an empty string

2024-08-06 06:18 UTC, Jarred-Sumner commented on src/StandaloneModuleGraph.zig
> +                    _ = bun.default_allocator.resize(bytes, data.len);
resize won't reduce memory usage here, seems like a footgun

2024-08-06 06:18 UTC, Jarred-Sumner commented on src/js_ast.zig
> +            const utf16_decode = try bun.js_lexer.decodeStringLiteralEscapeSequencesToUTF16(try s.string(allocator), allocator);
worst case this clones the string 3 times

2024-08-06 20:51 UTC, merged

2024-08-15 06:38 UTC, Jonatthu commented
@Jarred-Sumner bun build src/index.ts --target bun --compile --minify --sourcemap --outfile ./build/apps/server/app
With this command on sentry I still get 
<img width="761" alt="image" src="https://github.com/user-attachments/assets/6344d114-9584-4f71-b1e1-82b6f70cf5a1">

2024-08-15 06:49 UTC, Jarred-Sumner commented
@Jonatthu prior to this PR, that likely would've shown a callstack pointing to the internal compiled file, or just "processTicksAndRejections"

what you're seeing looks like an issue where we're not preserving async stack frames from napi, which would be unrelated to this PR. 

can you file an issue?

2024-08-15 08:38 UTC, Jonatthu commented
I am using latest bun 1.1.24 on azure linux container 
@Jarred-Sumner should I file to where?
Another example:
<img width="777" alt="image" src="https://github.com/user-attachments/assets/7d9ca3f6-a75d-4d00-ac88-bea6b04eb6c8">