fix(node:http): use a unique FakeSocket per socketId. only fire conne…
oven-sh/bun pull request #13254
Opened 2024-08-12 22:57 UTC by billywhizz

### What does this PR do?

- Partially Fixes https://github.com/oven-sh/bun/issues/13088

### Notes/Investigation

https://gist.github.com/billywhizz/ff5382889152d8f9d357a6de0c10fae1

### Description

- This PR, instead of creating a ```FakeSocket``` for every request, will surface the socketIdentifier to node:http module which will now only create a new ```FakeSocket``` for each socketIdentifier that doesn't exist in it's ```Map``` of active sockets. 
- The overhead is minimal for a local release build against current Bun release - ~1.5% on macos. this overhead may go away with a CI build?

### Questions/Issues

- we seem to have always created a new ```FakeSocket``` instance for **every** request. was this by design - for a particular reason - or just something we did to get over an issue? it obv. adds unnecessary overhead but also, in case of this memory leak, it is a big problem when the middleware is using each socket instance as the key into it's Map. apart from the memory leak, it means all their counts for requests per socket will be 1 maximum. 

```JavaScript
server.on('connection', (socket) => {
    console.log(`server.onconnection`);
    this.requestCountPerSocket.set(socket, 0);
    console.log(socket.constructor.name)
    socket.once('close', () => {
        console.log('socket.once.close')
        this.requestCountPerSocket.delete(socket)
    });
});
server.on('request', (req, res) => {
    this.requestCountPerSocket.set(req.socket, (this.requestCountPerSocket.get(req.socket) ?? 0) + 1);
    res.once('finish', () => {
        const pending = (this.requestCountPerSocket.get(req.socket) ?? 0) - 1;
        console.log(`response.onfinish ${pending}`)
        this.requestCountPerSocket.set(req.socket, pending);
        if (this.stopped && pending === 0) {
            console.log(`req.socket.end`)
            req.socket.end();
        }
    });
});
```

- In my PR i am creating a single ```FakeSocket``` per socketidentifier, which i have surfaced to JS, but i don't know if that will cause problems elsewhere - needs further testing.
- I am not sure how best to surface the close event for underlying sockets to the node:http module. any advice appreciated.

### TODO

- run existing tests
- add specific tests for this issue to ensure memleak is not happening
- handle and test with other kinds of sockets where ```FakeSocket``` is used
- handle the misidentification of the connection as a ```secureConnection```
- Surface/handle the socket close event in node:http module and fire the 'close' event to any listeners when it is received. without this, the middleware in question will keep existing sockets in it's internal map after they are closed, which is a memory leak, but obv. one that will happen at a much slower rate than currently given we don't now create a ```FakeSocket``` on every request.

### Other Notes

- after this change, we don't see the explosive memory growth and memory usage on macos is ~150MB compared to ~230 MB for node.js. RPS is ~68k RPS versus 23k RPS for node.js.

2024-08-12 22:57 UTC, robobun commented
Your commit 2467f60e78163d28b3d075d247fbd285888c608e is building: [`#1722`](https://buildkite.com/bun/bun/builds/1722)
<!-- generated-comment id=oven-sh/bun#13254 -->

2024-08-13 00:36 UTC, Jarred-Sumner commented on src/bun.js/api/server.zig
> +        if (self.tagged_pointer.as(HTTPServer.RequestContext).getNativeHandle()) |handle| {
This would be needed for each type matching the tagged pointer, not just the one type here.

2024-08-13 00:37 UTC, Jarred-Sumner commented on src/bun.js/api/server.zig
> +        pub fn socketId(_: *ThisServer, request: *JSC.WebCore.Request) JSC.JSValue {
This doesn't need to be a public, user-facing method.

This can instead be a private function only used in node:http.

2024-08-13 00:38 UTC, Jarred-Sumner commented on src/js/node/http.ts
> +    if (socketMap.has(this.#id)) {
We can skip the `.has` call, `delete` returns true if the key matched
```suggestion
    if (socketMap.delete(this.#id)) {
```

2024-08-13 00:39 UTC, Jarred-Sumner commented on src/bun.js/api/server.classes.ts
> +      requestSocketId: {
No need for a public API here

```suggestion

```

2024-08-13 00:43 UTC, Jarred-Sumner commented on src/js/node/http.ts
> +const socketMap = new Map(); // keep track of active sockets so we can handle socket events correctly
```suggestion
const socketMap = new Map(); // keep track of active sockets so we can handle socket events correctly
const socketIdFromRequest = $newZigFunction("server.zig", "socketIdFromRequest", 2);
```

2024-08-13 00:45 UTC, Jarred-Sumner requested changes
- We don't need to expose a user-facing API for this
- It might be better to do this in uWebSockets, it could involve a change to `AsyncSocket.h`

2024-08-13 14:04 UTC, billywhizz commented on src/bun.js/api/server.zig
> +        if (self.tagged_pointer.as(HTTPServer.RequestContext).getNativeHandle()) |handle| {
thanks - yeah, i had deleted those while testing. i just put this up as a draft to get some feedback on the approach first.

2025-06-24 00:42 UTC, closed without merging