Added rounded borders for `bun outdated` table
oven-sh/bun pull request #13505
Opened 2024-08-24 09:04 UTC by okineadev

### What does this PR do?

Makes rounded corners in the table

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### Description

In my opinion, the rounded corners are more pleasing to the eye and more modern

### How did you verify your code works?

- [ ] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [ ] I included a test for the new code, or an existing test covers it
- [ ] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed
- [ ] I wrote TypeScript/JavaScript tests and they pass locally (`bun-debug test test-file-name.test`)

2024-08-24 12:56 UTC, xhyrom approved these changes

2024-08-24 17:48 UTC, okineadev commented
@Jarred-Sumner please review

2024-08-24 21:23 UTC, evanwashere requested changes
This further restricts what fonts and text renderers can be used to see/hear/describe bun output. I would only consider this change if it required an additional flag/environment variable that the user had to set manually.

And some fonts don't have equal border width or layout for rounded corners compared to the current character set in use.

2024-08-25 03:52 UTC, okineadev commented
> This further restricts what fonts and text renderers can be used to see/hear/describe bun output. I would only consider this change if it required an additional flag/environment variable that the user had to set manually.
> 
> And some fonts don't have equal border width or layout for rounded corners compared to the current character set in use. <img alt="image" width="174" src="https://private-user-images.githubusercontent.com/70155278/361172375-2d191016-2993-400b-9bd6-ed96858d82d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NTYzMzgsIm5iZiI6MTcyNDU1NjAzOCwicGF0aCI6Ii83MDE1NTI3OC8zNjExNzIzNzUtMmQxOTEwMTYtMjk5My00MDBiLTliZDYtZWQ5Njg1OGQ4MmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDAzMjAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NDU1NGVhMjM3MjI3OWQ1NjVlZmExNTdiMWE4OGExNGZmYmIyYTFkYTNkNDljMzUxZTNiNzZiMmFlNjBhZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-se4UgnCi7GEEV6JYus_w647rX5H2eJJ2ziH10vjrHw">

Making a separate flag or environment variable to get rounded corners is probably too much

2025-06-28 04:48 UTC, nektro commented
sorry we didnt get to this sooner; no thank you. in agreement with the comments from others

2025-06-28 04:48 UTC, closed without merging