Make the V8_UNIMPLEMENTED error include the function name
oven-sh/bun pull request #13559
Opened 2024-08-27 02:52 UTC by Jarred-Sumner

### What does this PR do?

Make the V8_UNIMPLEMENTED error include the function name

### How did you verify your code works?

Didn't

2024-08-27 02:52 UTC, robobun commented
@Jarred-Sumner, your commit 1c7c96311791ce6e31d347186ae3efbc820be6a2 is building: [`#2397`](https://buildkite.com/bun/bun/builds/2397)
<!-- generated-comment id=oven-sh/bun#13559 -->

2024-08-28 18:49 UTC, 190n requested changes
current version doesn't compile

2024-08-28 18:49 UTC, 190n commented on src/bun.js/bindings/v8/v8.h
> +    }
```suggestion
#define V8_UNIMPLEMENTED()                                                                                          \
    do {                                                                                                            \
        const auto str = WTF::makeString(                                                                           \
            "You're using a module which calls a V8 function \""_s,                                                 \
            WTF::ASCIILiteral::fromLiteralUnsafe(__PRETTY_FUNCTION__),                                              \
            "\" that Bun does not yet implement. Track progress at https://github.com/oven-sh/bun/issues/4290."_s); \
        auto utf8 = str.utf8();                                                                                     \
        Bun__panic(utf8.data(), utf8.length());                                                                     \
    } while (0)
```

2024-08-31 01:04 UTC, 190n approved these changes

2024-08-31 01:52 UTC, merged