windows: fix sometimes crash when FDImpl.uv() is called on stdio
oven-sh/bun pull request #13719
Opened 2024-09-04 02:07 UTC by nektro

Closes https://github.com/oven-sh/bun/issues/13653
Closes https://github.com/oven-sh/bun/issues/13705
Closes https://github.com/oven-sh/bun/issues/13702
Closes https://github.com/oven-sh/bun/issues/11401

2024-09-04 02:07 UTC, robobun commented
@nektro, your commit 7ff3680cf97d43fa786472234100e8c86fd1955b is building: [`#2704`](https://buildkite.com/bun/bun/builds/2704)
<!-- generated-comment id=oven-sh/bun#13719 -->

2024-09-04 03:52 UTC, Jarred-Sumner commented
can you add a test

2024-09-07 01:21 UTC, Jarred-Sumner commented
The test segfaulted

2024-09-07 01:23 UTC, paperdave approved these changes
unfortunate that system tagged fds are introduced somewhere for the standard io handles, but this fix makes sense.

2024-09-07 01:23 UTC, paperdave commented on src/fd.zig
> +                        fn is_stdio_handle(id: w.DWORD, handle: w.HANDLE) bool {
instead of declaring a struct with a function here, why not just move the function above `pub fn uv`?

2024-09-07 01:25 UTC, Jarred-Sumner requested changes
Can’t merge until the test passes on windows

2024-09-07 04:00 UTC, merged