Add a couple uv symbols
oven-sh/bun pull request #13808
Opened 2024-09-08 10:13 UTC by Jarred-Sumner

### What does this PR do?

Adds `uv_os_getpid` and `uv_os_getppid`

because https://github.com/CodSpeedHQ/codspeed-node/blob/f2c6054a88227504cdc44b44ba811e632e7bae04/packages/core/src/native_core/linux_perf/linux_perf_listener.cc#L11

### How did you verify your code works?

2024-09-08 10:13 UTC, robobun commented
@Jarred-Sumner, your commit a299ed69bb171840b1cc825c09e155c6c8ccb24c is building: [`#3135`](https://buildkite.com/bun/bun/builds/3135)
<!-- generated-comment id=oven-sh/bun#13808 -->

2024-09-09 21:50 UTC, 190n approved these changes

2024-09-09 22:09 UTC, 190n requested changes
Testing locally and I get `dyld: missing symbol called`. Something's wrong with the linking of these functions.

2024-09-10 18:31 UTC, 190n approved these changes

2024-09-10 18:32 UTC, 190n requested changes
doesn't build on windows

2024-09-10 21:00 UTC, 190n approved these changes

2024-09-12 07:13 UTC, merged