feat: support default test timeout in bunfig.toml
oven-sh/bun pull request #13988
Opened 2024-09-16 19:52 UTC by treyturner

### What does this PR do?
Adds support for configuring default test timeout in `bunfig.toml`.

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?
I manually tested the build.

I couldn't find automated tests that cover parsing of `bunfig.toml` or which prove that bunfig values are overridden by command line arguments, so I stopped short of introducing any. I'm happy to try and introduce some if needed, though some guidance would likely be required.

Some Zig files changed.
- [ ] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [ ] I included a test for the new code, or an existing test covers it
- [x] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed
- [ ] I wrote TypeScript/JavaScript tests and they pass locally (`bun-debug test test-file-name.test`)

2024-09-20 05:02 UTC, Jarred-Sumner requested changes
Thank you for this. Would you be able to add a test? I suggest putting it in `test/cli/test` and use `tempDirWithFiles` from `"harness"` to create a temp folder programmatically with the bunfig.toml. Probably set the default test timeout to something like 1 or 5 and then verify the process prints a timed out message

2024-09-20 05:02 UTC, Jarred-Sumner commented
> The caveat this creates is that specifying the default timeout via CLI will cause a non-standard value from bunfig.toml to be used instead. I'm not sure how to address this without more extensive changes that seem like overkill for such a corner case, but this is almost surely due to my inexperience with the project and Zig. Any assistance addressing this concern or improving this aspect would be greatly appreciated.

I think this block of code could be moved to run after the bunfig.toml is read:
https://github.com/oven-sh/bun/blob/ab07cf444d02971c6dbf6ade0f3f016eb515f75f/src/cli.zig#L456-L528

2024-09-22 16:55 UTC, treyturner commented
> > The caveat this creates is that specifying the default timeout via CLI will cause a non-standard value from bunfig.toml to be used instead. I'm not sure how to address this without more extensive changes that seem like overkill for such a corner case, but this is almost surely due to my inexperience with the project and Zig. Any assistance addressing this concern or improving this aspect would be greatly appreciated.
> 
> I think this block of code could be moved to run after the bunfig.toml is read:
> 
> https://github.com/oven-sh/bun/blob/ab07cf444d02971c6dbf6ade0f3f016eb515f75f/src/cli.zig#L456-L528

10-4, thanks! Will likely be a few days before I can look at this again in detail, but it's on my TODO list.

2024-09-23 11:29 UTC, treyturner commented
Ok, I've got the tests for this pushed, including an extra test that I plan to delete before merge. Will be looking at the implementation next chance I get.

2024-09-23 15:12 UTC, treyturner commented
Ok @Jarred-Sumner, ready for another look when you get time!

2024-10-01 16:45 UTC, treyturner commented
This is good to go from my perspective, but I'll pop in every now and again to rebase from main and would be happy to address any further concerns or change requests.

2024-11-20 03:42 UTC, treyturner commented
Hi @Jarred-Sumner, would you be willing to give this another look? Would love to get this over the line.

2025-06-11 08:16 UTC, closed without merging