dont leak the address string in UDPSocket.addressToString
oven-sh/bun pull request #14127
Opened 2024-09-24 09:32 UTC by nektro

2024-09-24 09:32 UTC, robobun commented
@nektro, your commit bf8f70436c73cf4f7890ea06bb3b14f7c4aaff5d is building: [`#3788`](https://buildkite.com/bun/bun/builds/3788)
<!-- generated-comment id=oven-sh/bun#14127 -->

2024-09-24 21:15 UTC, cirospaciari commented on src/bun.js/api/bun/udp_socket.zig
> +        return str.transferToJS(globalThis);
nice finding

2024-09-25 17:51 UTC, cirospaciari requested changes
Can we add a memory leak test on UDP sockets?

2024-09-26 01:12 UTC, merged

2024-09-26 01:13 UTC, Jarred-Sumner commented
oh i pressed merge before I saw your comment