no need to cache protocol in NewServer when its statically known
oven-sh/bun pull request #14128
Opened 2024-09-24 09:35 UTC by nektro

2024-09-24 09:35 UTC, robobun commented
@nektro, your commit f177f7c1a02146883d0ef31687e31db79626e6e8 is building: [`#3789`](https://buildkite.com/bun/bun/builds/3789)
<!-- generated-comment id=oven-sh/bun#14128 -->

2024-09-24 21:13 UTC, cirospaciari commented on src/bun.js/api/server.zig
> +            return ZigString.static(if (ssl_enabled) "https" else "http").toJS(globalThis);
```suggestion
            return String.static(if (ssl_enabled) "https" else "http").toJS(globalThis);
```

2024-09-25 17:50 UTC, cirospaciari requested changes
We should prefer bun.String.static over ZigString

2024-09-25 21:46 UTC, cirospaciari approved these changes

2024-09-25 21:47 UTC, merged