Integrate CSS with bundler
oven-sh/bun pull request #14281
Opened 2024-10-01 22:52 UTC by zackradisic

### What does this PR do?

Parses, prints, minifies CSS in the bundler in canary or debug builds.

2024-10-01 22:53 UTC, robobun commented
@zackradisic, your commit c7912b6d3e4ece39467cf680497820c1e6ca998e is building: [`#4185`](https://buildkite.com/bun/bun/builds/4185)
<!-- generated-comment id=oven-sh/bun#14281 -->

2024-10-02 02:04 UTC, paperdave requested changes
note: did not review all code closely, but i think there wont be ~~real issues outside of canary where this flag is enabled~~ nvm there are currently test regressions

2024-10-02 02:04 UTC, paperclover commented on src/css/printer.zig
> +    const getWrittenAmt = struct {
why not put this as a function within the `struct {` closure. this anonymous struct is not needed.

2024-10-02 02:04 UTC, paperclover commented on src/bundler/bundle_v2.zig
> +            // TODO: css
stale comment

2024-10-02 02:04 UTC, paperdave commented on src/bundler/bundle_v2.zig
> +            const key = try temp_allocator.dupe(u8, entry_bits.bytes(this.graph.entry_points.len));
unused

2024-10-02 02:04 UTC, paperdave commented on src/bundler/bundle_v2.zig
> +        // const prev_action = if (Environment.isDebug) bun.crash_handler.current_action;
remove comment or uncomment

2024-10-03 10:43 UTC, Jarred-Sumner commented
merge conflikcts

2024-10-04 05:36 UTC, Jarred-Sumner commented on src/linker.zig
> +                        if (strings.hasSuffixComptime(import_record.path.text, ".css")) {
✂️

2024-10-05 03:23 UTC, merged