fix jsx symbol collisions when importing own variables with same names
oven-sh/bun pull request #14343
Opened 2024-10-04 03:15 UTC by snoglobe

### What does this PR do?

fixes #14021 - importing and using something that shares a name with a JSX symbol caused an import collision and a strange reference error. underlying cause was the symbol collision was not properly handled (plus some legacy code that needed to be removed). 

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?

2024-10-04 03:15 UTC, robobun commented
@snoglobe, your commit 8a8f7c1f86ea7ca2ccc4e7a81970b06b81514980 is building: [`#4365`](https://buildkite.com/bun/bun/builds/4365)
<!-- generated-comment id=oven-sh/bun#14343 -->

2024-10-08 07:43 UTC, Jarred-Sumner requested changes
test failures

2024-10-08 23:53 UTC, snoglobe commented
fixed

2024-10-09 01:00 UTC, paperdave requested changes

2024-10-09 01:00 UTC, paperclover commented on src/js_parser.zig
> +                                    const I_FUCKING_HATE_LLDB = p.jsxImport(.Fragment, expr.loc);
inline constant into single usage. tbh the label can alos just be named tag to match

2024-10-09 01:00 UTC, paperdave commented
reasonable otherwise.

2024-10-10 02:15 UTC, Jarred-Sumner commented on src/js_parser.zig
> +                                    const I_FUCKING_HATE_LLDB = p.jsxImport(.Fragment, expr.loc);
Please don't name variables like this in Bun's codebase.

2024-10-10 02:18 UTC, snoglobe commented
forgot to remove it 😓

On Wed, Oct 9, 2024 at 7:16 PM Jarred Sumner ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/js_parser.zig
> <https://github.com/oven-sh/bun/pull/14343#discussion_r1794490382>:
>
> > @@ -16374,7 +16269,8 @@ fn NewParser_(
>                                          break :tagger p.jsxStringsToMemberExpression(expr.loc, p.options.jsx.fragment) catch unreachable;
>                                      }
>
> -                                    break :tagger p.jsxImport(.Fragment, expr.loc);
> +                                    const I_FUCKING_HATE_LLDB = p.jsxImport(.Fragment, expr.loc);
>
> Please don't name variables like this in Bun's codebase.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/oven-sh/bun/pull/14343#discussion_r1794490382>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGC3MRECCLT2ATMFKSX35L3Z2XPO5AVCNFSM6AAAAABPLAL7EKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNJYGY4TIOBVG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-10 23:13 UTC, Jarred-Sumner commented
merge conflicts again

2024-10-10 23:27 UTC, snoglobe commented
fixed

2024-10-11 00:05 UTC, paperdave approved these changes

2024-10-11 02:42 UTC, Jarred-Sumner requested changes
bundler npm test is failing.
<img width="1036" alt="image" src="https://github.com/user-attachments/assets/e51446ca-5967-4647-ac00-b3cb28a86a30">

2024-10-19 23:39 UTC, fel1x-developer commented
Any updates? This bug is blocking some projects to upgrading bun from <1.1.28 , such as honojs.

2024-10-20 22:06 UTC, Jarred-Sumner commented
This also needs to update the runtime transpiler cache version before it can be merged.

2024-10-22 01:36 UTC, snoglobe commented
fixed

2024-10-22 07:17 UTC, merged