pm: add some missing npm_ env vars
oven-sh/bun pull request #14786
Opened 2024-10-24 05:44 UTC by nektro

Closes https://github.com/oven-sh/bun/issues/73
Closes https://github.com/oven-sh/bun/issues/2793

2024-10-24 05:46 UTC, robobun commented
@nektro, your commit 52684c19b9916e14b79bbec5450ab6c1539f4588 is building: [`#5249`](https://buildkite.com/bun/bun/builds/5249)
<!-- generated-comment id=oven-sh/bun#14786 -->

2024-10-24 21:38 UTC, dylan-conway commented on src/resolver/package_json.zig
> +                if (json.asProperty("config")) |config_prop| {
this looks identical to the block above, might be a handy helper something like `config_prop.e_object.createStringMap()`

2024-10-24 21:45 UTC, dylan-conway reviewed
A test should be added to `bun-workspace.test.ts` for multiple package.json with `config` fields

2024-10-25 15:30 UTC, hadarziv-army commented
It looks like it should close my issue too #13803

2024-11-21 01:36 UTC, dylan-conway requested changes
Could you also add a test for `npm_command` `publish` in `bun-install-registry.test.ts`

2024-11-22 23:11 UTC, dylan-conway approved these changes

2024-11-22 23:13 UTC, merged

2024-11-23 08:07 UTC, whyman commented
This is awesome!