Fix 14687: minification bug Only remove arrays symbols from number if >= 0
oven-sh/bun pull request #14947
Opened 2024-11-01 18:07 UTC by EliLichtblau

### What does this PR do?

Fix [14687](https://github.com/oven-sh/bun/issues/14687). Negative numbers can't be propertyKey's without extra syntax
```ts
// enum.ts
export const enum Foo {
  foo = -1,
  bar = 1,
}
```
```ts
// index.ts
import { Foo } from './enum';
export const FooRecord = {
  [Foo.foo]: 'foo',
  [Foo.bar]: 'bar',
}
```
```ts
// build.ts
await Bun.build({ entrypoints: ['index.ts'], minify: true, outdir: '.' });
```
Old 
```ts
var a={-1:"foo",1:"bar"};export{a as FooRecord};

```

New 
```ts
var f={[-1]:"foo",1:"bar"};export{f as FooRecord};
```

2024-11-01 22:33 UTC, paperdave requested changes
can you add tests in test/bundler/bundler_edgecase.test.ts

- cross file enum inlining
- same file enum inlining
- literal -1

2025-02-09 03:58 UTC, RiskyMH commented
@paperclover i added tests for them, however there does seem to be some interesting minification (see the lines I commented)

for most of the `const enum` it already was fine as all are `[]` but for **same file enum** it wasn't but now all numbers also get that treatment (not just negative). 

Even if no negative in enum it is putting square brakes so there probably needs to be some other fixes here, but this PR indeed still does fix one case of invalid JS.

2025-02-09 03:59 UTC, RiskyMH commented on test/bundler/bundler_edgecase.test.ts
> +    },
this is the test that's behavior changes in the pr, all others stay the same

2025-06-28 05:01 UTC, nektro commented
merge conflicts and lack of response from OP. happy to followup review if they're resolved

2025-06-28 05:01 UTC, closed without merging