Introduce high-performance native addon API in `Bun.build`, starting with `build.onBeforeParse` hook
oven-sh/bun pull request #14971
Opened 2024-11-03 12:20 UTC by Jarred-Sumner

### What does this PR do?

This lets you run concurrent third-party native plugins in `Bun.build` with practically zero API overhead. 

The goal is to provide enough of an API surface area to performantly support libraries that need to traverse every file (like Tailwind and eventually react-intl/formatjs) and loaders for specific file types (Hermes/FlowType, mdx, yaml)

This works as C API, leveraging Bun's existing FFI support.

Plugins can export a C function with the following signature:
```c
void onBeforeParse(int version, OnBeforeParseArguments *args, OnBeforeParseResult *result);
```

Unlike `onLoad`, the `onBeforeParse` hook runs synchronously before the code is parsed on the thread inside the threadpool. It's automatically concurrent (unlike `onLoad` which is single-threaded waiting on the JS event loop).

This hook lets plugins:
- Lazily fetch the source code
- Report build errors
- Mutate the source code in-place
- Set the loader
- Return new source code (and call a finalizer when the build ends to free the source code)

Plugins can be registered the same way as normal, except the the `onBeforeParse` function takes an FFI function as the callback value.

```js
import myNativePlugin from './my-native-plugin';
import {build} from 'bun';

await build({
  entrypoints: ["./index.ts"],
  plugins: [myNativePlugin],
});
```

<details>

<summary>The C header file looks like this currently</summary>

```c
#include <stddef.h>
#include <stdint.h>

typedef int8_t bun_log_level_t;
static const bun_log_level_t BunLogLevelError = 0;
static const bun_log_level_t BunLogLevelWarn = 1;
static const bun_log_level_t BunLogLevelInfo = 2;
static const bun_log_level_t BunLogLevelDebug = 3;

typedef uint8_t bun_loader_t;
static const bun_loader_t BunLoaderJsx = 0;
static const bun_loader_t BunLoaderJs = 1;
static const bun_loader_t BunLoaderTs = 2;
static const bun_loader_t BunLoaderTsx = 3;
static const bun_loader_t BunLoaderCss = 4;
static const bun_loader_t BunLoaderFile = 5;
static const bun_loader_t BunLoaderJson = 6;
static const bun_loader_t BunLoaderToml = 7;
static const bun_loader_t BunLoaderWasm = 8;
static const bun_loader_t BunLoaderNapi = 9;
static const bun_loader_t BunLoaderBase64 = 10;
static const bun_loader_t BunLoaderDataurl = 11;
static const bun_loader_t BunLoaderText = 12;

typedef uint8_t bun_target_t;
static const bun_target_t BunTargetBrowser = 0;
static const bun_target_t BunTargetNode = 1;
static const bun_target_t BunTargetBun = 2;

typedef struct BunLogOptions {
  const unsigned char *message_ptr;
  size_t message_len;

  const unsigned char *path_ptr;
  size_t path_len;

  const unsigned char *source_line_text_ptr;
  size_t source_line_text_len;

  bun_log_level_t level;

  int line;
  int lineEnd;
  int column;
  int columnEnd;
} BunLogOptions;

typedef struct OnBeforeParseArguments {
  void *bun;
  const unsigned char *path_ptr;
  size_t path_len;
  const unsigned char *namespace_ptr;
  size_t namespace_len;

  bun_loader_t default_loader;
} OnBeforeParseArguments;

typedef struct OnBeforeParseResult {
  unsigned char *source_ptr;
  size_t source_len;
  bun_loader_t loader;

  int (*const fetchSourceCode)(const OnBeforeParseArguments *args,
                               struct OnBeforeParseResult *result);

  void *plugin_source_code_context;
  void (*free_plugin_source_code_context)(void *context);

  void (*const log)(const OnBeforeParseArguments *args, BunLogOptions *options);
} OnBeforeParseResult;

void onBeforeParse(int version, OnBeforeParseArguments *args, OnBeforeParseResult *result);
```

</details>

Then, the javascript plugin definition looks like this:

```ts
import { dlopen } from "bun:ffi";

function createHandle(addon) {
  return dlopen(addon, {
    bun_mdx_rs: {
      args: ["int", "pointer", "pointer"],
      returns: ["void"],
    },
  });
}
export default function loadPlugin({ addon }) {
  return {
    name: "mdx-rs",
    setup(build) {
      const handle = createHandle(addon);
      build.onBeforeParse(
        // The first argument is the same as in onLoad and onResolve.
        {
          filter: /\.mdx?$/,
          namespace: "file",
        },
        handle.symbols.bun_mdx_rs,
      );
    },
  };
}
```

### How did you verify your code works?

Manually via a proof-of-concept plugin. This needs some tests before it can merge. I don't know how much the API should/needs to change

2024-11-03 12:20 UTC, robobun commented
@Jarred-Sumner, your commit 091e3313563be5106dcb92c2e7008691ec5ada24 is building: [`#5621`](https://buildkite.com/bun/bun/builds/5621)
<!-- generated-comment id=oven-sh/bun#14971 -->

2024-12-04 23:35 UTC, paperdave commented on packages/bun-build-mdx-rs/.gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/node
this gitignore is overkill

2024-12-04 23:36 UTC, paperdave commented on packages/bun-build-mdx-rs/.yarnrc.yml
> +nodeLinker: node-modules
yarn?

2024-12-05 00:01 UTC, paperdave requested changes

2024-12-05 00:01 UTC, paperclover commented on packages/bun-build-mdx-rs/index.d.ts
> +/* auto-generated by NAPI-RS */
we should not commit generated files

2024-12-05 00:01 UTC, paperclover commented on packages/bun-build-mdx-rs/npm/darwin-arm64/package.json
> +{
are these more generated files?

2024-12-05 00:01 UTC, paperclover commented on packages/bun-native-plugin-rs/headers/bun-native-bundler-plugin-api/bundler_plugin.h
> +#ifndef BUN_NATIVE_BUNDLER_PLUGIN_API_H
this file duplicates `packages/bun-native-bundler-plugin-api/bundler_plugin.h`
please gitignore this one

2024-12-05 00:01 UTC, paperclover commented on packages/bun-native-plugin-rs/src/lib.rs
> +    pub fn input_source_code(&mut self) -> Result<&'static str> {
this function should just return `&'a [u8]` (in zig `[]const u8`). the source code has not been validated to be valid utf-8 since we are blindly passing the file contents to the plugin, right?

2024-12-05 00:01 UTC, paperclover commented on src/bun.js/bindings/BunProcess.cpp
> +    // TODO: think about the finalizer here
you should think about this before merge (either implement the todo item or expand on the comment)

2024-12-05 00:01 UTC, paperclover commented on src/bun.js/bindings/BunProcess.h
> +void* bunDlopen(JSC::JSGlobalObject* globalObject, JSC::ThrowScope& scope, WTF::String& filename);
dead code?

2024-12-05 00:01 UTC, paperclover commented on src/bundler/bundle_v2.zig
> +            std.debug.assert(@sizeOf(OnBeforeParseArguments) == @sizeOf(headers.OnBeforeParseArguments));
bun.assert

2024-12-05 00:01 UTC, paperclover commented on src/bundler/bundle_v2.zig
> +        const headers = @cImport({
please dont use cImport, prefer build system

2024-12-05 00:01 UTC, paperclover commented on src/bundler/bundle_v2.zig
> +                // Allow the user to modify the loader
this comment doesnt add anything. the rest of the fields can also be modified by the user

2024-12-05 00:01 UTC, paperclover commented on src/bundler/bundle_v2.zig
> +            lineEnd: i32 = 0,
snake case

2024-12-05 00:01 UTC, paperclover commented on src/bundler/bundle_v2.zig
> +            struct_size: usize = @sizeOf(OnBeforeParseResult),
all the default fields in this struct besides struct_size should be removed. default fields cause mistakes

2024-12-05 00:01 UTC, paperclover commented on src/bundler/bundle_v2.zig
> +        const OnBeforeParseResultWrapper = struct {
remove default field

2024-12-05 00:01 UTC, paperclover commented on src/bundler/bundle_v2.zig
> +            struct_size: usize = @sizeOf(BunLogOptions),
remove all default field values

2024-12-05 00:01 UTC, paperclover commented on src/bundler/bundle_v2.zig
> +            context: *OnBeforeParsePlugin,
drefault field values except struct_size

2024-12-05 00:01 UTC, paperdave commented on src/crash_handler.zig
> +threadlocal var inside_native_plugin: bool = false;
change this to just being an optional pointer. use `null` to imply false

2024-12-05 00:01 UTC, paperdave commented on src/crash_handler.zig
> +            std.posix.SIG.KILL => .{ .segmentation_fault = addr },
you cannot intercept SIGKILL. If i am wrong, please add a new crash reason for killed. Killed shouldn't place the text "this is a bug in bun"

2024-12-05 06:07 UTC, paperdave approved these changes

2024-12-05 06:35 UTC, merged

2024-12-05 06:36 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +    auto* meta = new Bun::NapiModuleMeta(globalObject->m_pendingNapiModuleDlopenHandle);
wait 

this shouldn't exist

why does this exist