zig: make JSValue.toBunString use JSError
oven-sh/bun pull request #15295
Opened 2024-11-20 23:27 UTC by nektro

progress towards https://github.com/oven-sh/bun/issues/15141

2024-11-20 23:28 UTC, robobun commented
@nektro, your commit 762a1e70b5f3c3bb998a03f02b9c9d791214f8fd is building: [`#6503`](https://buildkite.com/bun/bun/builds/6503)
<!-- generated-comment id=oven-sh/bun#15295 -->

2024-11-23 08:53 UTC, Jarred-Sumner requested changes
We cannot merge this without tests that verify these bindings work.

2024-11-26 08:00 UTC, paperdave requested changes

2024-11-26 08:00 UTC, paperclover commented on src/bun.js/test/pretty_format.zig
> +                        message_string = message_prop.toBunString(this.globalThis) catch bun.String.static("(threw exception creating message)");
should this exception be cleared?

2024-11-26 08:00 UTC, paperclover commented on src/bun.js/web_worker.zig
> +        const str = err.toBunString(vm.global) catch bun.String.static("(threw exception creating message)");
should this exception be cleared?

2024-11-26 08:00 UTC, paperclover commented on src/bun.js/web_worker.zig
> +            if (resolveEntryPointSpecifier(parent, utf8_slice.slice(), error_message, &temp_log) catch return null) |preload| {
caller cannot differentiate error.OutOfMemory and error.JSError

2024-11-26 08:00 UTC, paperclover commented on src/bun.js/web_worker.zig
>          var preloads = std.ArrayList([]const u8).initCapacity(bun.default_allocator, preload_modules_len) catch bun.outOfMemory();
memory leak if line 206 returns.

2025-02-25 02:43 UTC, closed without merging