Rewrite most of napi_threadsafe_function
oven-sh/bun pull request #15309
Opened 2024-11-21 08:23 UTC by Jarred-Sumner

### What does this PR do?

Supersedes https://github.com/oven-sh/bun/pull/15289

### How did you verify your code works?

2024-11-21 08:23 UTC, robobun commented
@Jarred-Sumner, your commit 69c0a26eb350953ddec44ab3569c11a437ba6d25 is building: [`#6557`](https://buildkite.com/bun/bun/builds/6557)
<!-- generated-comment id=oven-sh/bun#15309 -->

2024-11-21 22:45 UTC, 190n requested changes

2024-11-21 22:45 UTC, 190n commented on src/napi/napi.zig
> +            return this.max_queue_size > 0 and this.count.load(.monotonic) >= this.max_queue_size;
Change all atomic ops in ThreadsafeFunction from `monotonic` to `seq_cst`

2024-11-21 22:45 UTC, 190n commented on src/napi/napi.zig
> +        defer this.lock.unlock();
These lines should be at the top of the function. Waiting on a condition variable requires the mutex to already be held by the waiting thread, and the mutex is re-acquired inside wait() before wait() returns.

2024-11-21 22:45 UTC, 190n commented on src/napi/napi.zig
> +        // This value will never change after initialization.
```suggestion
        /// This value will never change after initialization. Zero means the size is unlimited.
```

2024-11-21 22:45 UTC, 190n commented on src/napi/napi.zig
> +        count: std.atomic.Value(u32) = std.atomic.Value(u32).init(0),
Can we just use the count tracked by the fifo?

2024-11-21 22:45 UTC, 190n commented on src/napi/napi.zig
>              fun(this.event_loop.global, this.finalizer.data, this.ctx);
```suggestion
            const handle_scope = NapiHandleScope.open(this.env, false);
            defer if (handle_scope) |scope| scope.close(this.env);
            fun(this.event_loop.global, this.finalizer.data, this.ctx);
```

2024-11-22 12:44 UTC, merged

2024-11-26 21:26 UTC, ilijapuaca commented
@Jarred-Sumner question - could this somehow be connected to https://github.com/oven-sh/bun/issues/15291? I'm having a very hard time tracking the issue down, and the error in the other issue seems to reference a threadsafe function and gets triggered by Prisma usage.

I gave it a try with 1.1.37 and the issue still seems to be there