Make AbortSignal.timeout() 10x faster
oven-sh/bun pull request #15387
Opened 2024-11-24 10:53 UTC by Jarred-Sumner

### What does this PR do?

This makes it so the only usage of `us_create_timer` is the sweep and date timers used by `us_loop_t`. The GC timers and AbortSignal.timeout use the timer heap.  This will have memory usage implications so we need to measure memory usage changes in some scenarios before merging this.

This also switches the list of pending fetch() calls to shutdown to a HashMap instead of an ArrayHashMap, and swaps the multi-threaded queue of shutdowns

Stress test below gets 10x faster:
```js
❯ mem bun ~/Desktop/signals.js
[196.05ms] [100000x] fetch(url, { signal })
[239.94ms] [100000x] await Promise.all(promises)

Peak memory usage: 509 MB

❯ mem bun-1.1.36 ~/Desktop/signals.js
[2.19s] [100000x] fetch(url, { signal })
[4.66s] [100000x] await Promise.all(promises)

Peak memory usage: 503 MB
```

Code:
```
const count = 100_000;
import { createServer } from "http";

const server = createServer((req, res) => {
  res.end("Hello, world!");
});

const promises = new Array(count);
const listenPromise = Promise.withResolvers();

server.listen(0, () => {
  listenPromise.resolve();
});
await listenPromise.promise;
const port = server.address().port;

console.time("[" + count + "x] " + "fetch(url, { signal })");
for (let i = 0; i < count; i++) {
  const signal = AbortSignal.timeout(1);
  promises[i] = fetch(`http://localhost:${port}`, {
    signal,
  }).catch(() => {});
}
console.timeEnd("[" + count + "x] " + "fetch(url, { signal })");

console.time("[" + count + "x] " + "await Promise.all(promises)");
await Promise.all(promises);
console.timeEnd("[" + count + "x] " + "await Promise.all(promises)");

server.close();
```

### How did you verify your code works?

2024-11-24 10:53 UTC, robobun commented
@Jarred-Sumner, your commit f8e87e34d64ee1ee6c54dda5745ab0f5bd2755eb is building: [`#6785`](https://buildkite.com/bun/bun/builds/6785)
<!-- generated-comment id=oven-sh/bun#15387 -->

2024-12-06 18:51 UTC, cirospaciari requested changes
Tests failures

2024-12-06 20:42 UTC, kravetsone commented
Please make abortSignal timeout works (https://github.com/oven-sh/bun/issues/13302)

2024-12-06 22:36 UTC, cirospaciari commented
> Please make abortSignal timeout works (#13302)

Yes sir, you can follow the fix in this PR https://github.com/oven-sh/bun/pull/15623

2025-06-24 00:53 UTC, closed without merging