refactor: `KeyObject` helper functions return `JSCryptoKey`
oven-sh/bun pull request #15658
Opened 2024-12-08 23:04 UTC by DonIsaac

### What does this PR do?

Refactors helper functions in `KeyObject.cpp` to return `JSCryptoKey` objects instead of `EncodeJSValue`s. Prereq refactor to `KeyObject` JS -> native migration. Part of #15585.

### How did you verify your code works?
Tests already exist for this logic.

2024-12-08 23:04 UTC, robobun commented
Your commit c0ee1cca937e000390674d0725cdd649be869c7a is building: [`#7620`](https://buildkite.com/bun/bun/builds/7620)
<!-- generated-comment id=oven-sh/bun#15658 -->

2024-12-09 18:46 UTC, cirospaciari requested changes
Test failures

2024-12-09 19:04 UTC, cirospaciari commented on src/bun.js/bindings/KeyObject.cpp
> +            encodeKey(KeyObject__createOKPFromPrivate(globalObject, impl.exportKey(), impl.namedCurve(), wrapped.algorithmIdentifier()));
missing return

2024-12-09 19:06 UTC, DonIsaac commented on src/bun.js/bindings/KeyObject.cpp
> +            encodeKey(KeyObject__createOKPFromPrivate(globalObject, impl.exportKey(), impl.namedCurve(), wrapped.algorithmIdentifier()));
Fixed

2024-12-09 19:07 UTC, cirospaciari commented on src/bun.js/bindings/KeyObject.cpp
> +JSC::EncodedJSValue encodeKey(const std::optional<JSCryptoKey*> key)
I would choose another name here just to add what is being encoded and to what is being encoded example: encodeKeyObjectToJS

2025-05-19 15:29 UTC, closed without merging