feat(bundler): add --windows-icon, --windows-no-console, fix bun.exe's main icon
oven-sh/bun pull request #15894
Opened 2024-12-20 05:33 UTC by paperdave

Missing tests because writing one is very non-trivial.

`--windows-icon` is currently gated to windows build hosts (no cross compilation), as the current approach uses a library that calls the Windows API. In the future, we should replace this with a portable version that just manipulates the bytes in-memory.

Fixes #14062
Fixes #10823
Fixes #13084

2024-12-20 05:33 UTC, robobun commented
<div><sup>Updated 9:33 PM PT - Dec 19th, 2024</sup></div>

@dylan-conway, your commit 8116f33dd6648ee0f29dc8a2ae0cdc25ac256e3c is building: [`#8314`](https://buildkite.com/bun/bun/builds/8314)
<!-- generated-comment id=oven-sh/bun#15894 -->

2024-12-20 06:07 UTC, dylan-conway commented on src/cli.zig
> +        clap.parseParam("--windows-icon <STR>             When using --compile targetting Windows, assign an executable icon") catch unreachable,
```suggestion
        clap.parseParam("--windows-hide-console           When using --compile targeting Windows, prevent a Command prompt from opening alongside the executable") catch unreachable,
        clap.parseParam("--windows-icon <STR>             When using --compile targeting Windows, assign an executable icon") catch unreachable,
```

2024-12-20 06:21 UTC, dylan-conway approved these changes

2024-12-20 07:53 UTC, Jarred-Sumner requested changes
Does not successfully link on Windows.

> 
lld-link: error: codegen\windows-app-info.rc: unknown file type
--

2024-12-20 11:22 UTC, merged

2024-12-20 11:22 UTC, Jarred-Sumner commented
Does not fix Bun's own icon. But it's better than status quo.

2024-12-22 00:16 UTC, 716774 commented
I love bun ~

2024-12-25 17:45 UTC, CosmoMyzrailGorynych commented
@paperdave see [resedit-cli](https://www.npmjs.com/package/resedit-cli) and their [resedit](https://www.npmjs.com/package/resedit) and [pe-library](https://www.npmjs.com/package/pe-library) npm packages for a purely JS solution for patching windows executables. I've been already using them for Neutralino, NW.JS and Bun binaries for a long time to edit and sign windows executables in a Linux CI.

`resedit-cli` has a nice programmatic API despite being primarily a CLI tool. You might want to use `resedit` directly to exclude unneeded bulk.

2024-12-25 17:48 UTC, CosmoMyzrailGorynych commented
[Here is what I'm doing in my Buntralino](https://github.com/buntralino/buntralino-cli/blob/main/commands/build.ts#L70-L117) — I implemented icon addition and no-console before that PR.

2025-02-02 08:17 UTC, Nanome203 commented
> Does not fix Bun's own icon. But it's better than status quo.

Bun's main icon stopped appearing since v1.1.28