Add documentation for threadsafe option in FFI JSCallback
oven-sh/bun pull request #15982
Opened 2024-12-24 12:02 UTC by citkane

### What does this PR do?

It documents the `threadsafe` option for FFI `JSCallback`.
It resolves #15925 

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?

2024-12-27 22:11 UTC, DonIsaac approved these changes

2025-01-06 22:12 UTC, 190n requested changes

2025-01-06 22:12 UTC, 190n commented on docs/api/ffi.md
> +    threadsafe: true // Optional. Defaults to `false`
Thanks for addressing missing documentation. I think it'd be better to describe `threadsafe` in a separate section, and explain what it does rather than just demonstrating that it is an option that exists. The `threadsafe` option isn't necessary in this example so it could be confusing to see it set to `true`.

I think we should also state that `threadsafe` is experimental for now since there are cases where it doesn't 100% work.

2025-01-06 22:31 UTC, citkane commented on docs/api/ffi.md
> +    threadsafe: true // Optional. Defaults to `false`
That may be true, but setting up a new documentation structure for Bun is out of scope for me as a user. I am not a Bun developer.

All I can add is to articulate my user experience of being frustrated for many days over this issue before I found the `threadsafe` flag in code. I have grown to like Bun,  but it was causing a roadblock for my scenario in this instance, and I was relieved that it was only a documentation issue. 

The documentation quickfix I am proposing may save much similar frustration in Bun userland.

2025-01-06 22:38 UTC, 190n commented on docs/api/ffi.md
> +    threadsafe: true // Optional. Defaults to `false`
> setting up a new documentation structure for Bun is out of scope for me as a user. I am not a Bun developer.

Sorry, I didn't mean add a whole new page or anything. I just meant a new paragraph or subheading under "Callbacks" on the existing `ffi.md`, rather than putting `threadsafe` in the existing example.

> All I can add is to articulate my user experience of being frustrated for many days over this issue before I found the threadsafe flag in code. I have grown to like Bun, but it was causing a roadblock for my scenario in this instance, and I was relieved that it was only a documentation issue.
>
> The documentation quickfix I am proposing may save much similar frustration in Bun userland.

I understand, and I'm sorry we hadn't documented this option before. I still think it's worth ensuring that the documentation is done right when we do add it.

2025-01-06 22:58 UTC, citkane commented on docs/api/ffi.md
> +    threadsafe: true // Optional. Defaults to `false`
PR has been updated.

2025-01-06 23:00 UTC, 190n approved these changes

2025-01-06 23:00 UTC, 190n commented on docs/api/ffi.md
> +    threadsafe: true // Optional. Defaults to `false`
Thank you! Looks good now.

2025-01-08 02:35 UTC, 190n commented
Sorry @citkane, I don't know why this didn't merge. I'll try running CI again. I don't think you need to be updating this against `main` as there aren't any conflicts. I think there is just some issue with our CI and contributor PRs.

2025-01-08 13:27 UTC, citkane commented
It was my initial bad for not updating my fork before committing the change.
Chaos ensued...

I see that all the checks and approvals have now passed, but still no merge. I will leave it to you to push the right buttons.

2025-01-08 20:08 UTC, merged