node: fix the rest of test-process
oven-sh/bun pull request #16026
Opened 2024-12-28 06:26 UTC by nektro

supercedes https://github.com/oven-sh/bun/pull/14621

not done, pushing now so the robobun comment is at the top

2024-12-28 06:26 UTC, robobun commented
<div><sup>Updated 10:26 PM PT - Dec 27th, 2024</sup></div>

@nektro, your commit 2ebba0a1ad438b91e1b92c174a668f1e3db161aa is building: [`#8624`](https://buildkite.com/bun/bun/builds/8624)
<!-- generated-comment id=oven-sh/bun#16026 -->

2025-01-03 01:08 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +        if (auto ntq = globalObject->m_nextTickQueue) {
This copies the `WriteBarrier`, which you didn't mean to do.
```suggestion
        if (globalObject->m_nextTickQueue) {
```

2025-01-03 01:08 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +            auto nextTickQueue = jsDynamicCast<JSNextTickQueue*>(ntq.get());
```suggestion
            auto nextTickQueue = jsCast<JSNextTickQueue*>(globalObject->m_nextTickQueue.get());
```

2025-01-03 01:09 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +    auto reallyExitVal = process->get(globalObject, Identifier::fromString(vm, "reallyExit"_s));
Can we track if `reallyExit` was created and skip calling it if it wasn't?

2025-01-03 01:10 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +    auto require_key = id_value.toString(globalObject);
We shouldn't call `toString` on the id_value twice.

2025-01-03 01:12 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +    return JSValue::encode(JSC::profiledCall(globalObject, ProfilingReason::API, fn, JSC::getCallData(fn), moduleObject, args));
Calling require on it is unnecessary work, and also means that the user can override the exports.

2025-01-03 01:21 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +    auto is_valid_bultin_name = Bun::isBuiltinModule(id_str);
This is a similar problem as in the validators causing performance regressions.

Instead of a validator which returns a boolean and then again is later validated, we should make this return a `std::variant<std::nullopt_t, InternalModuleRegistry::Field, NativeTag>`

```suggestion
    auto is_valid_bultin_name = Bun::isBuiltinModule(id_str);
```

When that `variant` returns `nullopt_t`, we know it's invalid
When that `variant` returns an `InternalModuleRegistry::Field`, we know it's a JS builtin
Otherwise we know it's a function to require and we call require on that.

2025-01-03 01:24 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +    auto dep_warning = jsString(vm, String("DeprecationWarning"_s));
Please don't create jsString unnecessarily.

2025-01-03 01:24 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +        type = jsString(vm, String("Warning"_s));
ditto

2025-01-03 01:27 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +    char buf[8192];
what is this buffer size based on? 8KB can be a lot

2025-01-03 01:27 UTC, heimskr commented on src/bun.js/bindings/BunProcess.cpp
> +    auto is_valid_bultin_name = Bun::isBuiltinModule(id_str);
I think [`std::monostate`](https://en.cppreference.com/w/cpp/utility/variant/monostate) instead of `std::nullopt_t` is more idiomatic to indicate an empty `std::variant`

2025-01-03 01:28 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +                userValue = comparator->get(globalObject, JSC::Identifier::fromString(vm, "user"_s));
is it because of proxies? what's the rationale?

2025-01-03 01:31 UTC, Jarred-Sumner commented on src/bun.js/bindings/NodeValidator.cpp
> +JSC::EncodedJSValue V::validateInteger(JSC::ThrowScope& scope, JSC::JSGlobalObject* globalObject, JSC::JSValue value, ASCIILiteral name, JSC::JSValue min, JSC::JSValue max)
None of the usages of this warrant using `JSC::JSValue` for `min` or `max`. Let's avoid the extra work and pass an int32_t instead.

And, instead of returning a JSC::EncodedJSValue, we should return `int32_t`

or you could use the IDL converters for this

2025-01-03 01:32 UTC, Jarred-Sumner commented on src/bun.js/bindings/bindings.cpp
> +    JSC::JSObject* result = JSC::ErrorInstance::create(globalObject, JSC::ErrorInstance::createStructure(vm, globalObject, globalObject->errorPrototype()), message, options);
Why was this reverted?

2025-01-03 01:33 UTC, Jarred-Sumner commented on src/bun.js/bindings/ErrorCode.cpp
> +    auto arg_kind = arg_name.contains("."_s) ? "property"_s : "argument"_s;
Use `'.'` instead of `""_s` since it's a single byte
```suggestion
    auto arg_kind = arg_name.contains('.') ? "property"_s : "argument"_s;
```

2025-01-03 01:33 UTC, Jarred-Sumner commented on src/bun.js/bindings/ErrorCode.cpp
> +    auto arg_kind = arg_name.contains("."_s) ? "property"_s : "argument"_s;
Use `'.'` instead of `""_s` since it's a single byte
```suggestion
    auto arg_kind = arg_name.contains('.') ? "property"_s : "argument"_s;
```

2025-01-03 01:35 UTC, Jarred-Sumner commented on src/bun.js/bindings/ErrorCode.cpp
> +JSC::EncodedJSValue ASSERTION(JSC::ThrowScope& throwScope, JSC::JSGlobalObject* globalObject, JSC::JSValue msg)
Instead of adding more functions, modify the one at the bottom to throw this message by default when `$ERR_ASSERTION` is passed through JS.

2025-01-03 01:35 UTC, Jarred-Sumner commented on src/bun.js/bindings/ErrorCode.cpp
> +JSC::EncodedJSValue ASSERTION(JSC::ThrowScope& throwScope, JSC::JSGlobalObject* globalObject, JSC::JSValue msg)
Assuming this was meant for JS, otherwise ignore me if not

2025-01-03 01:35 UTC, Jarred-Sumner commented on src/bun.js/bindings/ErrorCode.cpp
> +JSC_DEFINE_HOST_FUNCTION(jsFunction_ERR_IPC_ONE_PIPE, (JSC::JSGlobalObject * globalObject, JSC::CallFrame* callFrame))
Instead of adding more functions, modify the one at the bottom to throw this message by default when `$ERR_IPC_ONE_PIPE,` is passed through JS.

2025-01-03 01:36 UTC, Jarred-Sumner commented on src/bun.js/bindings/NodeValidator.cpp
> +#include "wtf/text/ASCIILiteral.h"
```suggestion

```

2025-01-03 01:37 UTC, Jarred-Sumner commented on src/bun.js/bindings/helpers.cpp
> +const char* errno_string(int errorno)
Don't we already have all these strings in Zig? Wouldn't this be duplicating the strings in the binary? Couldn't we expose a function to get those strings instead?

2025-01-03 01:39 UTC, Jarred-Sumner commented on src/bun.js/bindings/exports.zig
> +        if (bun.CLI.Bun__Node__ProcessTitle) |_| bun.default_allocator.free(bun.CLI.Bun__Node__ProcessTitle.?);
This needs a mutex guarding it

2025-01-03 01:41 UTC, Jarred-Sumner commented on src/sys.zig
> +pub fn chdirOSPath(path: bun.stringZ, destination: if (Environment.isPosix) bun.stringZ else bun.string) Maybe(void) {
Why was this changed to always be a stringZ? The string conversion is unnecessary on Windows

2025-01-03 01:43 UTC, Jarred-Sumner requested changes
Some comments, let me know when ready for another pass

2025-01-03 02:58 UTC, nektro commented on src/bun.js/bindings/BunProcess.cpp
> +    char buf[8192];
https://github.com/nodejs/node/blob/v22.9.0/src/node_credentials.cc#L142-L145

2025-01-03 23:58 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.h
> +    bool m_reportOnUncaughtException;
Let's default initialize this to false to avoid undefined memory
```suggestion
    bool m_reportOnUncaughtException = false;
```

2025-01-03 23:59 UTC, Jarred-Sumner commented on src/bun.js/bindings/ErrorCode.cpp
> +    auto message = makeString("`process.setupUncaughtExceptionCapture()` was called while a capture callback was already active"_s);
`makeString` allocates a String. We don't need to allocate the string here - just the string literal is fine

2025-01-04 00:02 UTC, Jarred-Sumner commented on src/bun.js/bindings/NodeValidator.cpp
> +JSC::EncodedJSValue V::validateInteger(JSC::ThrowScope& scope, JSC::JSGlobalObject* globalObject, JSC::JSValue value, ASCIILiteral name, JSC::JSValue min, JSC::JSValue max)
This comment was marked as resolved but I don't see where it was resolved?

2025-01-04 00:10 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +        type = jsString(vm, String("Warning"_s));
where was this resolved?

2025-01-04 00:10 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +    if (is_number) Bun::V::validateInteger(scope, globalObject, value, jsString(vm, String("id"_s)), jsNumber(0), jsNumber(std::pow(2, 31) - 1));
we are still creating JSString here unnecessarily

2025-01-04 00:10 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunProcess.cpp
> +    auto msgb = msg.toBoolean(globalObject);
```suggestion
    auto msgb = msg.toBoolean(globalObject);
    RETURN_IF_EXCEPTION(throwScope, {});
```

2025-01-04 00:33 UTC, nektro commented on src/bun.js/bindings/BunProcess.cpp
> +    auto msgb = msg.toBoolean(globalObject);
toBoolean can't throw

2025-01-04 01:55 UTC, nektro commented on src/bun.js/bindings/BunProcess.cpp
> +        type = jsString(vm, String("Warning"_s));
this value is passed to `putDirect` unmodified so it needs to be a JSValue

2025-01-04 01:56 UTC, nektro commented on src/bun.js/bindings/NodeValidator.cpp
> +JSC::EncodedJSValue V::validateInteger(JSC::ThrowScope& scope, JSC::JSGlobalObject* globalObject, JSC::JSValue value, ASCIILiteral name, JSC::JSValue min, JSC::JSValue max)
this wasnt modified as part of this pr so it felt more appropriate to change in a followup rather than balloon this one anymore

2025-01-04 02:06 UTC, Jarred-Sumner requested changes
We shouldn't make `error:` print as `Error:`
1) There are very likely 3rd-party scripts depending on this behavior
2) It's aesthetically worse

We can make whatever tests that specifically check for the string "Error:" instead check for "error:", or we can make sure it's using util.inspect isntead of Bun.inspect / console.log in the appropriate places.

2025-01-06 22:30 UTC, merged