refactor: consolidate allocators
oven-sh/bun pull request #16061
Opened 2024-12-30 17:53 UTC by DonIsaac

### What does this PR do?
Moves all memory allocators into `src/allocators`. The following allocators are affected:
- `NullableAllocator`
- `MimallocArena`
- `MaxHeapAllocator`
- `LinuxMemFdAllocator`
- All allocators in `memory_allocator.zig` (`CAllocator`, `ZAllocator`, `HugeAllocator`, etc)

2024-12-30 17:53 UTC, robobun commented
<div><sup>Updated 9:53 AM PT - Dec 30th, 2024</sup></div>

@DonIsaac, your commit e1d12670fd77d3c2b56ed61625124ea6afaa5e07 is building: [`#8665`](https://buildkite.com/bun/bun/builds/8665)
<!-- generated-comment id=oven-sh/bun#16061 -->

2025-01-06 23:51 UTC, dylan-conway commented on src/allocators/linux_memfd_allocator.zig
> +                std.debug.panic("LinuxMemFdAllocator ref_count underflow", .{});
let's throw this in a `if (Environment.isDebug) {... }` block. I'm not familiar with how/where this allocator is dereferenced, but we don't want to introduce a panic for something that could be a noop

2025-01-06 23:52 UTC, dylan-conway requested changes
Just one comment

2025-01-08 21:46 UTC, DonIsaac commented on src/allocators/linux_memfd_allocator.zig
> +                std.debug.panic("LinuxMemFdAllocator ref_count underflow", .{});
done

2025-01-08 21:49 UTC, dylan-conway approved these changes
Looks good

2025-01-09 00:08 UTC, merged