Implement `os.cpus` for Darwin (OS X)
oven-sh/bun pull request #2115
Opened 2023-02-20 19:20 UTC by jwhear

Fixes #1888.

Provides an implementation of `os.cpus` for Darwin platforms.

2023-02-20 19:21 UTC, jwhear commented on src/bun.js/node/node_os.zig
> +                    slice[cpu_index].model = try JSC.ZigString.init(model_name).clone(allocator);
Given that that line is just a slice into a local buffer, I changed this to a defensive copy.

2023-02-20 19:28 UTC, jwhear commented
Fun, it looks like `unistd.h` isn't available on macOS x86_64.
Update: this problem appears only for v10 (and presumably previous).

2023-02-20 22:38 UTC, ThatOneBro commented
Checking this out now on OSX 12 x86_64, will let you know if it works 👍

2023-02-21 00:48 UTC, Jarred-Sumner commented on src/bun.js/node/node_os.zig
> +            cpu.model = model_name_value;
This leaks memory

`StackFallbackAllocator` would be better because then using .toValueGC will clone it as expected

2023-02-21 00:52 UTC, ThatOneBro commented
Looks like the output is different from what we see in node

Here's a few:
- Looks like the sentinel value ended in the string as a null character literal for model
- For some reason the model also shows up as MacBook instead of the CPU name / brand
- I think the values for user and idle need to be converted to a milliseconds

Currently looking at node's source to see where they get the vendor "model" info from

Node's output:
<img width="606" alt="Screen Shot 2023-02-20 at 6 41 17 PM" src="https://user-images.githubusercontent.com/1592008/220220191-37b8b46a-7677-4a76-9819-a5843d03d8d9.png">

Bun's output:
<img width="301" alt="Screen Shot 2023-02-20 at 6 41 08 PM" src="https://user-images.githubusercontent.com/1592008/220220225-c5b6a80e-91fd-470a-b71d-0604caf1e606.png">

2023-02-21 19:52 UTC, ThatOneBro requested changes

2023-02-21 19:52 UTC, ThatOneBro commented on src/bun.js/node/node_os.zig
> +        if (std.c.sysctlbyname("machdep.cpu.brand_string", &model_name, &len, null, 0) != 0 or
I think for some reason this isn't short circuiting when it should. Not exactly sure why, but I think we are failing to get `machdep.cpu.brand_string` at least on my machine. It doesn't make much sense though because `libuv` appears to do the same thing and this works on Node for me.

2023-02-21 20:01 UTC, jwhear commented on src/bun.js/node/node_os.zig
> +        if (std.c.sysctlbyname("machdep.cpu.brand_string", &model_name, &len, null, 0) != 0 or
Ah, I think I need to `and` the two so that if the return code is zero it short-circuits.

2023-02-21 20:06 UTC, ThatOneBro commented on src/bun.js/node/node_os.zig
> +        if (std.c.sysctlbyname("machdep.cpu.brand_string", &model_name, &len, null, 0) != 0 or
Oh yeah you're right 😅 Easy solution

2023-02-22 18:06 UTC, jwhear commented
@ThatOneBro when you have a spare moment, could you try building and running my latest?  The `model` field should definitely be fixed, the `times` values might need debugging.

2023-02-24 16:13 UTC, jwhear commented
Needs one more check on OSX to ensure that the buffer overrun protection is correct, but this should be good to go.

2023-02-24 17:58 UTC, ThatOneBro commented
I'll check this out in a bit 👍

2023-02-24 20:22 UTC, ThatOneBro commented on src/bun.js/node/node_os.zig
> +        if (std.c.sysctlbyname("machdep.cpu.brand_string", &model_name, &len, null, 0) != 0 or
Looks like this is fixed
<img width="524" alt="Screen Shot 2023-02-24 at 2 19 38 PM" src="https://user-images.githubusercontent.com/1592008/221283997-91666afd-5cd0-4c69-b38e-44bb5046690e.png">

2023-02-24 20:23 UTC, ThatOneBro approved these changes
Looks good to me

2023-02-24 20:24 UTC, merged

2023-02-24 20:24 UTC, ThatOneBro commented
Thank you