fix: Fixed punctuation on homepage.
oven-sh/bun pull request #280
Opened 2022-07-06 18:40 UTC by mustafahasankhan

Congratulations on the launch, much excited for this project.
Fixed a punctuation on home page.

2022-07-06 22:12 UTC, nodeicode approved these changes

2022-07-06 22:15 UTC, nodeicode commented
changes are hard to read, tldr: this PR is changing 
```The goal of Bun is to run most of the world&apos;s JavaScript outside of browsers``` 
to 
```The goal of Bun is to run most of the worlds JavaScript outside of browsers```

2022-07-07 12:31 UTC, mustafahasankhan commented
> changes are hard to read, tldr: this PR is changing `The goal of Bun is to run most of the worlds JavaScript outside of browsers` to `The goal of Bun is to run most of the world&apos;s JavaScript outside of browsers`

Just added a missing apostrophe. `&apos;` denotes the apostrophe.

2022-07-07 14:45 UTC, tropicaaal commented
This is changing the compiled version of the webpage and not the actual source of it. You should probably be making your changes to src/page.tsx rather than anything in `public`.

2022-07-07 15:32 UTC, michellbrito requested changes
Don't edit the index.html instead edit the `src/page.tsx` like @Tropix126 mentioned

2022-07-08 18:02 UTC, mustafahasankhan commented
[Update] Added changes to source too.

2022-07-11 03:41 UTC, michellbrito requested changes, later dismissed

2022-07-11 03:41 UTC, michellbrito commented on packages/bun-landing/public/index.html
> +</style></head><body><div id="header-wrap"><header><a href="/" id="logo-link"><img height="61px" src="/logo@2x.png" alt="Bun" id="logo"/><img height="31.65px" src="/Bun@2x.png" alt="Bun" id="logo-tex
Undo the changes to the index.html so its changes is handle when its compiled from the page.tsx

2022-07-13 21:38 UTC, FinnRG commented
@mustafahasankhan Could you please undo the changes to the build output?

2022-07-14 17:29 UTC, mustafahasankhan commented
> @mustafahasankhan Could you please undo the changes to the build output?

Done!

2022-07-14 18:17 UTC, FinnRG approved these changes

2022-07-14 18:20 UTC, merged