feat(bun/test): Implement "toSatisfy"
oven-sh/bun pull request #3268
Opened 2023-06-10 05:56 UTC by TiranexDev

`expect(value).toSatisfy(function)`, the function passed to "toSatisfy" function is called with the value in expect, so it's almost the same as calling:

`expect(function(value)).toBeTrue();`
More about it: https://vitest.dev/api/expect.html#tosatisfy

What I already have done:

- [x] Types
- [x] Testing
- [x] Implement toSatisfy itself

2023-06-10 19:25 UTC, TiranexDev commented
I'll upload the bindings and stuff when someone reviewed my code and it's ready to be merged.

2023-06-11 16:26 UTC, Electroid requested changes
Thanks for working on this, left a few comments for review.

2023-06-11 16:26 UTC, Electroid commented on src/bun.js/test/jest.zig
> +        };
There is a more efficient way to do this, that doesn't require allocation. Instead of checking `isNumber()` in the code before this highlight, you can use `isAnyInt()`.

2023-06-11 16:26 UTC, Electroid commented on src/bun.js/test/jest.zig
> +        const expected_line = "Expected to include: <green>{any}<r> <green>{any}<r> times \n";
How about this:

* If times = 0: `Expected to not include: {}`
* If times = 1: `Expected to include: {}`
* If times > 1: `Expected to include: {} ({} times)`
* If not and times = 0: `Expected to include: {}`
* If not and times = 1: `Expected not to include: {}`
* If not and times > 1: `Expected not to include: {} ({} times)`

2023-06-11 16:26 UTC, Electroid commented on src/bun.js/test/jest.zig
> +        if (!right.jsType().isFunction()) {
```suggestion
        if (!right.isCallable(globalThis)) {
```

2023-06-11 16:26 UTC, Electroid commented on src/bun.js/test/jest.zig
> +        const right = arguments[0];
"right" and "left" aren't really descriptive. the expect value can be "value" and the argument can be "predicate"

2023-06-11 16:26 UTC, Electroid commented on src/bun.js/test/jest.zig
> +        var pass = right.call(globalThis, &.{left}).toBoolean();
We should print the result of the satisfy function, for example:

```zig
var result = predicate.call(globalThis, &{value});
if (result.toError()) |err| {
  // Predicate threw an error: {}
} else {
  // Received: value
}
var pass = (result.isBoolean() and result.toBoolean()) != not;
```

2023-06-11 16:26 UTC, Electroid commented on test/js/bun/test/expect.test.ts
> +  test("toIncludeRepeated()", () => {
Should add test cases for:
* n = 0
* n = 0 with not
* value is empty string
* include is empty string
* both value and include are empty strings
* emoji strings

2023-06-20 05:41 UTC, Jarred-Sumner commented on src/bun.js/test/jest.zig
> +        const countAsNum = std.fmt.parseInt(u32, count.toString(globalThis).toSlice(globalThis, default_allocator).slice(), 10) catch {
We shouldn't use the zig std lib function for this. Instead, I think we can use .toNumber? One of the functions in JSValue will call `[Symbol.toPrimitive()]` and pass it a `"number"` which would do the coercions equivalent to `Number(string)` in JS.

2023-06-20 06:10 UTC, v3nntrnx commented on src/bun.js/test/jest.zig
> +        const countAsNum = std.fmt.parseInt(u32, count.toString(globalThis).toSlice(globalThis, default_allocator).slice(), 10) catch {
I‘ll be on it when I come home

2023-07-16 21:50 UTC, TiranexDev commented
I'll open a new one, my git has some troubles

2023-07-16 21:50 UTC, closed without merging