Fix path_watcher
oven-sh/bun pull request #3920
Opened 2023-08-01 16:07 UTC by cirospaciari

### What does this PR do?

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

Existing tests

2023-08-01 19:17 UTC, Jarred-Sumner requested changes
This does not fix it? The `finalized` field is set to true in the same scope  as the struct is destroyed, which means all cases the struct  is used after finalized is a use after free. 

https://github.com/oven-sh/bun/blob/044a6facdb3dd624b65960fd390de24980df4989/src/bun.js/node/path_watcher.zig#L816

2023-08-01 19:30 UTC, cirospaciari commented
> finalized

It's only used when `pending_directories > 0` (on another thread) finalized just say that the owner is gone, when the last task ends/cancel it will call deinit again (but not emit/flush).

2023-08-01 19:32 UTC, Jarred-Sumner commented
It's not threadsafe though. The finalized boolean would need to be loaded and stored atomically with a @fence to ensure memory ordering. But even that's not safe because the other thread could be accessing it after deinit

2023-08-01 19:36 UTC, cirospaciari commented
> It's not threadsafe though. The finalized boolean would need to be loaded and stored atomically with a @Fence to ensure memory ordering. But even that's not safe because the other thread could be accessing it after deinit

I used mutex to guarantee access to `finalized` and `pending_directories` but I found another mistake let me finish it

2023-08-01 19:49 UTC, Jarred-Sumner commented
Not all usages are locked by a mutex. If it were, it would hang until after it’s freed and then segfault

2023-08-02 01:42 UTC, Jarred-Sumner commented on src/bun.js/node/path_watcher.zig
> +                        manager._decrementPathRef(entry_path_z);
dead lock

2023-08-02 01:44 UTC, Jarred-Sumner commented on src/bun.js/node/path_watcher.zig
> +                    if (watcher.refPendingDirectory()) {
dead lock

2023-08-02 01:44 UTC, Jarred-Sumner commented on src/bun.js/node/path_watcher.zig
> +                if (watcher.refPendingDirectory()) {
dead lock

2023-08-02 01:44 UTC, Jarred-Sumner commented on src/bun.js/node/path_watcher.zig
> +            if (manager.refPendingTask()) {
dead lock

2023-08-02 10:54 UTC, cirospaciari commented on src/bun.js/node/path_watcher.zig
> +                if (watcher.refPendingDirectory()) {
manager uses a different lock from watcher

2023-08-02 10:54 UTC, cirospaciari commented on src/bun.js/node/path_watcher.zig
> +            if (manager.refPendingTask()) {
unlock with defer before context exits

2023-08-02 20:00 UTC, merged

2023-08-02 20:00 UTC, Jarred-Sumner commented
Thank you