Support for  completion in Bash
oven-sh/bun pull request #403
Opened 2022-07-08 01:21 UTC by zombieleet

This PR aims at adding full support for completion in bash.

2022-07-08 09:23 UTC, evanwashere requested changes
autocomplete for files is missing? eg `bun run t[TAB]` -> `bun run test.js`
[install.sh](https://github.com/Jarred-Sumner/bun/blob/44ee4caf6ffb62a3cc6d6b76124c718d2842fa87/src/cli/install.sh) needs to be modified to automatically install bash completions if it's bash shell

2022-07-08 13:55 UTC, zombieleet commented
> autocomplete for files is missing? eg `bun run t[TAB]` -> `bun run test.js` [install.sh](https://github.com/Jarred-Sumner/bun/blob/44ee4caf6ffb62a3cc6d6b76124c718d2842fa87/src/cli/install.sh) needs to be modified to automatically install bash completions if it's bash shell

Thanks, I will check this out

2022-07-13 10:27 UTC, evanwashere approved these changes

2022-07-25 07:47 UTC, Jarred-Sumner commented
This is great!

2022-07-25 07:47 UTC, merged