Align `process.nextTick` execution order with Node
oven-sh/bun pull request #4409
Opened 2023-08-30 13:52 UTC by Jarred-Sumner

### What does this PR do?

In Node, `process.nextTick` runs before microtasks are drained. Previously, Bun was treating `process.nextTick` as the same queue as the microtask queue. This led to subtle bugs.

Fixes #4252, probably others

The code is loosely based on https://github.com/nodejs/node/blob/main/lib/internal/process/task_queues.js. The main difference is that our implementation is lazier and we don't emit on unhandledexception callbacks currently.

### How did you verify your code works?

A couple tests. Have to avoid referencing the process object inside outer function to avoid causing it to infinite loop. Using the `$createFIFO` builtin creates too large of an array in stress tests, causing an infinite loop. That's why it uses this fixed buffer abstraction from node. 

I think we will need to make one small tweak to support AsyncLocalStorage, but @paperdave will know more about that than me

2023-08-30 18:59 UTC, paperdave requested changes
I've been checking with node and this implementation is incorrect, `nextTick` runs after `queueMicrotask` as of node 20. Hopefully switching this around isn't too hard, but I don't think `onEachMicrotaskTick` will do the trick.

```ts
let resolve;
let promise = new Promise(res => {
  resolve = res;
});

const order = [];
let nextTickI = 0;
let microtaskI = 0;
let remaining = 20;
let runs = [];
for (let i = 0; i < 10; i++) {
  queueMicrotask(() => {
    runs.push(queueMicrotask);
    order.push("queueMicrotask " + microtaskI++);
    if (--remaining === 0) resolve(order);
  });
  process.nextTick(() => {
    runs.push(process.nextTick);
    order.push("process.nextTick " + nextTickI++);
    if (--remaining === 0) resolve(order);
  });
}

await promise;

console.log(order);
```
yields:

![image](https://github.com/oven-sh/bun/assets/24465214/735ba0a2-6bf7-4bb2-a8d1-a71aeb43e0cf)

I'm going to update the tests to reflect this, as well as use jest as a baseline to ensure that they pass on node too.

2023-08-30 18:59 UTC, paperdave commented on src/bun.js/bindings/ZigGlobalObject.cpp
> +            vm.setOnEachMicrotaskTick(nullptr);
why is the handler cleared here? it doesn't seem to ever be restored.

also we now need to coordinate this with the async_hooks `setOnEachMicrotaskTick` overwriting this handler temporarily.

I will push some tests that hit these edge cases

2023-08-30 19:22 UTC, paperdave commented
Actually, I'm incorrect. Having this not be at the top level in node causes the order to be as you implemented it.

```diff
 let resolve;
 let promise = new Promise(res => {
   resolve = res;
 });

 const order = [];
 let nextTickI = 0;
 let microtaskI = 0;
 let remaining = 20;
 let runs = [];
 for (let i = 0; i < 10; i++) {
+  process.nextTick(() => {
     queueMicrotask(() => {
       runs.push(queueMicrotask);
       order.push("queueMicrotask " + microtaskI++);
       if (--remaining === 0) resolve(order);
     });
     process.nextTick(() => {
       runs.push(process.nextTick);
       order.push("process.nextTick " + nextTickI++);
       if (--remaining === 0) resolve(order);
     });
+  });
 }

 await promise;

console.log(order);
```

![image](https://github.com/oven-sh/bun/assets/24465214/7379f81e-c8fe-4366-a5ef-22a0075bd214)

I'm sure you checked this page: https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick#phases-overview

2023-08-31 02:12 UTC, paperdave approved these changes
merge if tests pass

2023-09-05 00:32 UTC, Jarred-Sumner commented
Tests do not pass, we need to address the exit code issue and possibly this readline promises test failure

2023-09-05 21:26 UTC, Jarred-Sumner commented
Let’s merge after tests run (you’ll need to fix the conflicts)

2023-09-06 00:52 UTC, merged