hono example with typescript
oven-sh/bun pull request #577
Opened 2022-07-11 13:21 UTC by Jesse-Lucas1996

hono example with typescript

2022-07-11 13:25 UTC, xhyrom requested changes
Please delete .gitignore, it's not in any example.

2022-07-11 13:42 UTC, xhyrom commented
why are you adding dom to lib?

2022-07-11 13:54 UTC, Jesse-Lucas1996 commented
That's a good question, brain is fried

2022-07-11 14:59 UTC, xHyroM requested changes
`port` variable is defined

2022-07-11 14:59 UTC, xHyroM commented on examples/hono/src/index.ts
> +  port: 3000,
```suggestion
  port,
```

2022-07-12 05:06 UTC, Jesse-Lucas1996 commented
Is this good to get merged in?

2022-07-12 05:29 UTC, xHyroM approved these changes

2022-07-12 06:43 UTC, Jesse-Lucas1996 commented
Sweet, just merge in when can. I don't have write access

2022-07-12 08:53 UTC, FinnRG commented
@Jesse-Lucas1996 When I try to run ``bun run start``, I get the following error (even if I specify the PORT env variable):
```
$ cd src && bun run index.ts
2 | 
3 | const app = new Hono();
4 | const home = app.get("/", (c) => {
5 |   return c.json({ message: "Hello World!" });
6 | });
7 | console.log(`Running at http://localhost:${port}`);
                                              ^
 ReferenceError: Can't find variable: port
      at /home/fg/Projects/hono-template/examples/hono/src/index.ts:7:43
Script error "start" exited with 1 status

```

2022-07-12 08:56 UTC, Jesse-Lucas1996 commented
Ah yes I know the issue will fix soon

2022-07-12 09:02 UTC, Jesse-Lucas1996 commented
@FinnRG I accidently removed code in update. All good to go now

2022-07-12 09:15 UTC, FinnRG requested changes

2022-07-12 09:15 UTC, FinnRG commented on examples/hono/package.json
> +    "start": "cd src && bun run index.ts"
Sorry for all the small nitpicks, but could you change this to ``bun run src/index.ts``?

2022-07-12 09:32 UTC, FinnRG requested changes

2022-07-12 09:32 UTC, FinnRG commented on examples/hono/readme.md
> +When cloned, run bun install
Bun installs dependencies automatically after ``bun create``

2022-07-12 09:42 UTC, Jesse-Lucas1996 commented
@FinnRG and done :) nit pick away!! I love learning better or more refined ways

2022-07-12 09:45 UTC, FinnRG approved these changes

2022-07-12 09:46 UTC, merged

2022-07-12 09:46 UTC, FinnRG commented
Thank you!