fix: support console,dir options object correctly
oven-sh/bun pull request #6059
Opened 2023-09-26 00:20 UTC by liz3

`console.dir` can be passed a second argument which is a object of options. This implements that logic with the currently supported properties: `depth` and `colors`.
I used node as a reference for implementation details.

Fixes: https://github.com/oven-sh/bun/issues/6039

### What does this PR do?

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

- [x] I or my editor ran `zig fmt` on the changed files
- [x] I included a test for the new code, or an existing test covers it

2023-09-26 00:51 UTC, paperdave requested changes

2023-09-26 00:51 UTC, paperdave commented on src/bun.js/bindings/exports.zig
> +                var depth_prop = opts.get(global, "depth") orelse JSValue.zero;
instead of `orelse ...`, use `if (opts.get(...)) |depth_prop| {` this way

2023-09-26 00:51 UTC, paperdave commented on src/bun.js/bindings/exports.zig
> +                    print_options.max_depth = depth_prop.toU16();
`toU16` will crash if given a float.

2023-09-26 08:59 UTC, liz3 commented
@paperdave ive implemented request ed changes

2023-09-26 23:11 UTC, paperdave approved these changes
looks good will merge after tests run

2023-09-27 02:47 UTC, merged

2023-09-27 02:47 UTC, paperdave commented
thank you