fix: correctly prepend system path to relative urls on `pathToFileURL`
oven-sh/bun pull request #6472
Opened 2023-10-12 22:41 UTC by liz3

The `pathToFileURL` was not handling the case that when a relative link is passed, it should convert it to a absolute url and prepend the top_folder, or otherwise described, resolve the path before creating the url.

This does that by calling into buns Path api and using its `resolve` function.

Theres the detail that i used preprocessor directives to determine whether we are on windows because there does not seam to be a easy way to get that at runtime in the `BunObject.cpp` file.

Fixes: https://github.com/oven-sh/bun/issues/6456

### What does this PR do?

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

- [x] I included a test for the new code, or an existing test covers it

2023-10-17 00:05 UTC, paperdave requested changes

2023-10-17 00:05 UTC, paperclover commented on src/bun.js/bindings/BunObject.cpp
> +    auto path = JSC::JSValue::encode(callFrame->uncheckedArgument(0));
uncheckedArgument will crash if the argument is not provided. since this is user exposed we cannot assume this

2023-10-17 00:05 UTC, paperdave commented on src/bun.js/bindings/BunObject.cpp
> +    // i dont know a runtime way to check this, help
TIL `#if OS(WINDOWS)`. we can use that here

2023-10-17 01:34 UTC, liz3 commented
@paperdave addressed reviews!

2023-10-17 01:41 UTC, paperdave commented
what's the reason it has to be a runtime check, i think inlining the boolean true or false is fine

2023-10-17 01:47 UTC, liz3 commented
> what's the reason it has to be a runtime check, i think inlining the boolean true or false is fine

@paperdave there is no inherit reason for it to be runtime checked, but when i was implementing the fix i first thought about implementing this myself but then when counterchecking this would require some more complex logic thought it might be more worth using existing logic, i.e the path module, the c++ binding for the path module sets a [internal property](https://github.com/oven-sh/bun/blob/main/src/bun.js/bindings/Path.cpp#L44-L45) on the global object which is runtime defined and so i didn't want to break that pattern but was unable to find a quick way of accessing it which made a preprecessor directive more reasonable.

2023-11-01 06:18 UTC, paperdave approved these changes

2023-11-06 21:56 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunObject.cpp
```suggestion
  RETURN_IF_EXCEPTION(throwScope, {});
```

2023-11-06 21:56 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunObject.cpp
> +  RETURN_IF_EXCEPTION(throwScope, {});
```suggestion
   RETURN_IF_EXCEPTION(throwScope, {});
```

2023-11-06 21:56 UTC, Jarred-Sumner commented on src/bun.js/bindings/BunObject.cpp
> +   RETURN_IF_EXCEPTION(throwScope, {});
```suggestion
    RETURN_IF_EXCEPTION(throwScope, {});
```

2023-11-06 21:57 UTC, merged