Begin working on CI tasks for bun-framework-next
oven-sh/bun pull request #65
Opened 2021-11-11 19:02 UTC by hanford

- Add typed polyfills for URL & TextEncoded/Decoder
- Add prettier to root
- Adds some boilerplate for executing actions on GH
- Adds Next & Typescript as DevDeps for `bun-framework-next` (Next remains a peer dependency as well)
- Consolidate empty files / references to a single `empty.js`

2021-11-11 19:06 UTC, hanford commented on .github/workflows/bun-framework-next.yml
> +        os: [macOS-latest]
This doesn't have to run on macOS, I don't have any preference (can easily be ubuntu)

2021-11-11 21:35 UTC, Jarred-Sumner commented
tbh I don't think it makes sense to use pnpm workspaces for Bun because it makes building more complicated than npm and, right now at least, there aren't shared dependencies between packages

2021-11-11 21:37 UTC, Jarred-Sumner commented
The rest of this looks good though

2021-11-11 22:21 UTC, hanford commented
@Jarred-Sumner Happy to remove the PNPM workspace bit, but I was imagining linking `bun-framework-next` with the example next.js app for testing, which PNPM does make easier (especially vs NPM/yarn link)


Anyways, mostly indifferent here

2021-11-11 22:46 UTC, Jarred-Sumner approved these changes

2021-11-11 22:47 UTC, Jarred-Sumner commented
Also worth noting the current integration test https://github.com/Jarred-Sumner/bun/blob/main/integration/apps/bun-create-next.sh

It fails if the request doesn't 200, which is good because that response is SSR'd via Bun.js

2021-11-16 00:24 UTC, hanford commented on packages/bun-framework-next/client.development.tsx
> -  _boot(EntryPointNamespace).then(() => {}, false);
don't think this was needed

2021-11-16 00:25 UTC, hanford commented on packages/bun-framework-next/client.development.tsx
> -function TopLevelRender({ App, Component, props, scroll }) {
scroll wasn't used in AppContainer

2021-11-16 00:25 UTC, hanford commented on packages/bun-framework-next/client.development.tsx
> -      <App Component={<div>UH OH!!!!</div>} pageProps={data.props}></App>
This was causing typescript errors for `Component` not matching the same type as AppComponent, I _think_ that's ok?

2021-11-16 00:26 UTC, hanford commented on packages/bun-framework-next/page-loader.ts
> +    link.onerror = reject;
This should be the same but these lines have been problematic in the past

2021-11-23 04:56 UTC, Jarred-Sumner commented on packages/bun-framework-next/client.development.tsx
> -      reactRoot = ReactDOM.createRoot(domEl, reactEl);
I think this needs a rebase? I changed this the other day

2021-11-23 04:57 UTC, Jarred-Sumner commented on packages/bun-framework-next/page-loader.ts
> +    link.onerror = reject;
`onerror` has a difference but I think it's an acceptable difference. Instead of rejecting with undefined, it rejects with what onerror returns

2021-11-23 04:58 UTC, Jarred-Sumner commented on packages/bun-framework-next/renderDocument.tsx
> -import * as ReactDOMServer from "react-dom/server.browser";
I believe this has to be `.browser` because it may choose a Node.js version otherwise, which expects Node.js streams

2021-11-23 05:00 UTC, Jarred-Sumner commented on packages/bun-framework-next/renderDocument.tsx
> +  const getStaticProps = (PageNamespace as any).getStaticProps || null;
Can `PageNamespace` be `undefined` or `null`? I'm not sure.

2021-11-23 05:01 UTC, Jarred-Sumner commented on packages/bun-framework-next/renderDocument.tsx
> +    pages[name] = [origin + filePath];
`Bun.origin` is a special builtin getter which turns it into an absolute URL. I believe this change is safe though.

2021-11-23 05:02 UTC, Jarred-Sumner commented on packages/bun-framework-next/renderDocument.tsx
> +    autoExport: isAutoExport,
Pedantically, these don't have the same meaning, but if you tested it and it still works then seems fine

2021-11-23 05:05 UTC, Jarred-Sumner commented on packages/bun-framework-next/server-polyfills.tsx
> +import { TextEncoder, TextDecoder } from "fast-text-encoding";
Can we inline the dependency into a file in `bun-framework-next`? The polyfill is temporary, doesn't need updates, and I would rather the code be easier for us to read/understand

2021-11-23 05:08 UTC, Jarred-Sumner requested changes
Two changes:
- Can we inline `fast-text-encoding` into a file? I prefer to avoid third-party dependencies for simple things
- Does `react-dom/server` work still? Were you able to test SSR works correctly after these changes?

2021-11-23 15:18 UTC, hanford commented on packages/bun-framework-next/client.development.tsx
> -      reactRoot = ReactDOM.createRoot(domEl, reactEl);
I'll double check, TS doesn't like the current way, createRoot doesn't take a second arg ... it may need to be ```createRoot(domEl).render(reactEl)``` or something

![image](https://user-images.githubusercontent.com/2148168/143051374-3e6b1084-fde8-4413-ab57-81ee6fa8ad71.png)

2021-11-23 15:38 UTC, hanford commented on packages/bun-framework-next/renderDocument.tsx
> +  const getStaticProps = (PageNamespace as any).getStaticProps || null;
Not certain, that's why I was leaving the `|| {}`

2021-11-23 15:41 UTC, hanford commented on packages/bun-framework-next/server-polyfills.tsx
> +import { TextEncoder, TextDecoder } from "fast-text-encoding";
that's fine, I was just opting for something with ts types

2021-11-23 16:04 UTC, hanford commented on packages/bun-framework-next/client.development.tsx
> -      reactRoot = ReactDOM.createRoot(domEl, reactEl);
_I think what I have is right_

https://github.com/vercel/next.js/blob/7f58a2e49f7c4cc0c23e6c814eac2c9ce3ee7bd7/packages/next/client/index.tsx#L536

2021-11-23 21:36 UTC, hanford commented on packages/bun-framework-next/client.development.tsx
> +          Component: info.Component || CachedComponent,
This change fixes instances of shallowing routing

2021-11-24 00:34 UTC, hanford commented
SSR is still working btw
![image](https://user-images.githubusercontent.com/2148168/143150082-9e31aa4e-4819-4996-90bc-87b18b161f3f.png)

2021-11-24 00:35 UTC, merged