fix(console) ignore class methods in console.log output
oven-sh/bun pull request #6654
Opened 2023-10-22 14:07 UTC by almmiko

### What does this PR do?

Fixes https://github.com/oven-sh/bun/issues/4223

### How did you verify your code works?

If Zig files changed:

- [x] I or my editor ran `zig fmt` on the changed files
- [x] I included a test for the new code, or an existing test covers it

2023-10-24 06:20 UTC, Jarred-Sumner commented on src/bun.js/bindings/exports.zig
> +                    if (value.jsType().isFunction()) {
What happens if it's a function defined on the instance but not on the prototype? 

```js
class FooBar {
  constructor() {
    this.abc = () => {};
  }
  method() {
    return 42;
  }
}
```

In node, this logs
```js
FooBar { abc: [Function (anonymous)] }
```

2023-10-24 06:21 UTC, Jarred-Sumner requested changes
This change likely needs to be done in `forEachProperty` C++ binding and not in the Zig code as we do not have the information to know whether the properties are the prototype's properties or the instance.

<img width="350" alt="image" src="https://github.com/oven-sh/bun/assets/709451/0e4f9dff-37e7-4b08-90f1-3ab57beba69a">

2023-11-01 13:25 UTC, almmiko commented
Hey @Jarred-Sumner thanks for highlighting the possible place where the change should be made.

2024-01-18 05:43 UTC, jdalton approved these changes

2024-07-09 20:21 UTC, Jarred-Sumner commented
Closing due to bitrot

2024-07-09 20:21 UTC, closed without merging