Enable debug build of JSC in development by default, add to CI
oven-sh/bun pull request #7027
Opened 2023-11-10 10:56 UTC by Jarred-Sumner

### What does this PR do?

- Use the debug build of JSC by default in development
- Use the debug build of mimalloc in development
- Add a build of Bun in CI which uses the debug build of JSC and ReleaseSafe build of Zig (linux only for now)
- Enable assertions in ReleaseSafe
- Disable spurious mimalloc warnings so that CI doesn't fail

### How did you verify your code works?

Locally, but lets see if CI works

2023-11-10 11:15 UTC, paperdave commented on scripts/build-mimalloc.sh
> +rm -rf CMakeCache* CMakeFiles
if we have this, please rm build-mimalloc-debug.sh

2023-11-10 11:17 UTC, paperdave commented
looks good, but i do not think the entire suite of tests will pass with assertions on. still probably best we do this change

2023-11-10 11:19 UTC, paperdave commented on src/env.zig
> +pub const allow_assert = isDebug or isTest or std.builtin.Mode.ReleaseSafe == @import("builtin").mode;
this is fine but `std.debug.runtime_safety` is a boolean for this type of thing

2023-11-10 11:25 UTC, paperdave requested changes
overall good.

- one comment that requires attention
- kinda wish arm mac had an assertions build but it's ok.
- are zig error return traces enabled? i think they are. that would be cool.

2023-11-10 11:25 UTC, paperdave commented on CMakeLists.txt
> +        add_compile_definitions("BUN_DEBUG=1")
this is likely incorrect. i was under the impression BUN_DEBUG is only when using bun-debug, not release with assertions. for if we are using JSC debug we have ENABLE_ASSERT.

if you want to keep this, this must change InternalModuleRegistry to use a different mechanism, as in `#if BUN_DEBUG` will use a filesystem loading mechanism that is not portable to other machines.

2023-11-10 11:25 UTC, paperdave commented on CMakeLists.txt
> +        add_compile_definitions("BUN_DEBUG=1")
You should change

```
static void maybeAddCodeCoverage(JSC::VM& vm, const JSC::SourceCode& code)
#ifdef BUN_DEBUG
```
to `#if ENABLE_ASSERT`

and so on in other places you want to enable extra assertion-related code.

2023-11-11 01:18 UTC, paperdave commented on CMakeLists.txt
> +        add_compile_definitions("BUN_DEBUG=1")
```diff
-add_compile_definitions("BUN_DEBUG=1")
```

2023-11-11 01:19 UTC, paperdave requested changes
need to remove definition for `BUN_DEBUG` in CMakeLists.txt or else the JSC debug build + release build will not be portable.

2023-11-11 01:20 UTC, paperdave commented on CMakeLists.txt
> +        add_compile_definitions("BUN_DEBUG=1")
idk how to do the suggestion thing

2023-11-11 03:41 UTC, paperdave approved these changes

2023-11-13 07:02 UTC, SeedyROM commented
Would this PR happen to affect this issue? https://github.com/oven-sh/bun/issues/7063

Seems like something was weird with the WTFStrings at GC.

2023-11-14 02:26 UTC, paperdave reviewed
this is certainly a lot of stuff. no major concerns

2023-11-14 02:26 UTC, paperclover commented on docs/project/contributing.md
can you update the date in this file:

```md
{% callout %}
We last updated Zig on **November 13th, 2023**
{% /callout %}
```

2023-11-14 02:26 UTC, paperclover commented on src/bun.js/bindings/BunString.cpp
> +WTF::String BunString::toWTFString() const
can you remove `Bun::toWTFString(const BunString& bunString)`, and also move the assertion that was defined in that variant of the function to this?

2023-11-14 02:26 UTC, paperclover commented on src/bun.js/bindings/CommonJSModuleRecord.cpp
> +    return Structure::create(vm, globalObject, globalObject->functionPrototype(), TypeInfo(ObjectType, StructureFlags), info());
i thought function prototypes need to be of function type but if it works it works. my mistake must be that it should not have been done on the prototype but just the actual structure.

2023-11-14 02:26 UTC, paperclover commented on src/bun.js/bindings/webcore/JSFetchHeaders.cpp
> +    } else if (size < JSFinalObject::maxInlineCapacity) {
<=

2023-11-14 02:26 UTC, paperclover commented on src/bun.js/bindings/webcore/JSURLSearchParams.cpp
> +    if (impl.size() + 1 < JSFinalObject::maxInlineCapacity) {
<=

2023-11-14 06:10 UTC, merged