template(kingworld): add kingworld template
oven-sh/bun pull request #708
Opened 2022-07-14 13:20 UTC by SaltyAom

Add template for [kingworld](https://github.com/saltyaom/kingworld) to use with `bun create`

2022-07-14 13:23 UTC, Kapsonfire-DE commented
yesterday they wanted me to copy the gitignore from next example
and dont name it .gitignore but `gitignore` without dot

2022-07-14 18:35 UTC, FinnRG requested changes
Thank you for your work. Your framework looks quite promising (I also like how you choose the name :D). I have only some minor consistency issues.

2022-07-14 18:35 UTC, FinnRG commented on examples/kingworld/package.json
> +  "author": "",
Please remove these empty fields

2022-07-14 18:35 UTC, FinnRG commented on examples/kingworld/gitignore
> +node_modules
Could you use the same gitignore as the ``next`` template? It's just to have some consistency between the templates.

2022-07-14 18:35 UTC, FinnRG commented on examples/kingworld/README.md
> +bun create kingworld
Please change this to ``bun create kingworld ./kingworld-example`` to emphasize that the user can choose their own folder.

2022-07-14 18:35 UTC, FinnRG commented on examples/kingworld/README.md
> +Go to http://localhost:3000 and enjoy your new awesome web server
Please use ``Open http://localhost:3000/ with your browser to see the result.`` like the other templates.

2022-07-14 18:35 UTC, FinnRG commented on examples/kingworld/README.md
> +# KingWorld Starter
Please use ``KingWorld with Bun runtime`` like the other templates.

2022-07-14 18:35 UTC, FinnRG commented on examples/kingworld/README.md
> +## Scaffold
Please use `´Getting Started`` like the other templates.

2022-07-14 19:23 UTC, Mr0nline commented on examples/kingworld/package.json
> +}
There should be EOFL!

2022-07-15 10:13 UTC, FinnRG requested changes

2022-07-15 10:13 UTC, FinnRG commented on examples/kingworld/README.md
> +To get start with this template, simply paste the command in to your terminal:
To get started with this template, simply paste this command in to your terminal:

2022-07-15 10:13 UTC, FinnRG commented on examples/kingworld/README.md
> +KingWorld is set with `nodemon` for auto reload, simply run:
KingWorld uses `nodemon` for auto reload. To start the development server run:

2022-07-15 11:53 UTC, FinnRG approved these changes

2022-07-15 11:53 UTC, FinnRG commented
LGTM, thank you for your work.

2022-07-15 11:54 UTC, merged