fix console.timeLog
oven-sh/bun pull request #7089
Opened 2023-11-13 12:21 UTC by lqqyt2423

fix console.timeLog data arguments aren't logged in output

https://github.com/oven-sh/bun/issues/3821

2023-11-13 12:51 UTC, Jarred-Sumner commented
Thank you for this 

Are the arguments supposed to be stringified? What happens if you pass a symbol? Where are the tests?

2023-11-14 10:10 UTC, lqqyt2423 commented
@Jarred-Sumner I changed code, and add some test.

2023-11-14 16:55 UTC, Electroid requested changes

2023-11-14 16:55 UTC, Electroid commented on test/js/web/console/console-timeLog.test.ts
> +    env: {
```suggestion
    env: bunEnv,
```

2023-11-14 16:55 UTC, Electroid commented on test/js/web/console/console-timeLog.test.ts
> +import { bunExe } from "harness";
```suggestion
import { bunExe, bunEnv } from "harness";
```

2023-11-15 02:23 UTC, paperdave commented on src/bun.js/bindings/exports.zig
> +            const arg = args[i];
```suggestion
        for (args[0..args_len]) |arg| {
```

2023-11-15 02:25 UTC, paperdave approved these changes

2023-11-16 18:16 UTC, paperdave commented
this test failure on linux x64 might be existing/flaky but it did trip:
 - `test/js/third_party/prisma/prisma.test.ts`
the code for this looks fine and is unrelated to the error i think.

2023-11-16 22:03 UTC, RadhiRasho commented on test/js/web/console/console-timeLog.js
> +console.timeLog("label");
```suggestion
console.timeLog("label");
console.timeEnd("labal");
```

2023-11-17 14:15 UTC, paperdave approved these changes

2023-11-17 14:57 UTC, paperdave commented
timeLog tests fail. i believe this is simply a mistake in the test itself?
<img width="1583" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/5c1da4f7-9705-46cf-ac6d-90be0eef57ae">

2023-11-17 15:02 UTC, lqqyt2423 commented
@paperdave fixed

2023-11-30 02:32 UTC, paperdave approved these changes

2023-11-30 04:07 UTC, merged

2023-11-30 04:07 UTC, paperdave commented
thanks!