Change `Bun.serve({ fetch })` types
oven-sh/bun pull request #7160
Opened 2023-11-16 21:24 UTC by Didas-git

### What does this PR do?

Since #7159 recieved the `typescript` tag i though that this was not intentional so i changed the fetch types so you can return whatever you want/not return.

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?

2023-11-16 21:30 UTC, paperdave requested changes
this is not correct. the fetch function should stay as returning Response, but we should also allow `void` only if websocket handlers are provided

2023-11-16 22:17 UTC, paperdave commented
this looks much better. i should've mentioned in the first review but also can you add a type test inside of `serve.test-d.ts`

2023-11-16 22:54 UTC, Didas-git commented
> this looks much better. i should've mentioned in the first review but also can you add a type test inside of `serve.test-d.ts`

Added a simple test, tell me if there is something else.

2023-11-17 13:22 UTC, paperdave approved these changes

2023-11-17 13:34 UTC, merged