Add jsx spread children support
oven-sh/bun pull request #7294
Opened 2023-11-24 08:43 UTC by rhyzx

### What does this PR do?

#### Example
```js
const a = <h1>{...[123]}</h1>
```
#### Output
##### Before: 
```sh
error: Unexpected ...
```
##### After:
```js
var a = jsx_dev_runtime.jsxDEV("h1", {
  children: [...[123]]
}, undefined, true, undefined, this);
```

This feature is already supported by most transpilers, eg:
[Typescript](https://www.typescriptlang.org/play?target=99&jsx=5#code/MYewdgzgLgBAhjAvDAPACwIwD4DeA6AgbQwCYBmAXQF8UB6TLAKCA)
[Esbuild](https://esbuild.github.io/try/#dAAwLjE5LjcAewogIGxvYWRlcjogJ2pzeCcsCiAganN4OiAnYXV0b21hdGljJywKfQA8ZGl2PnsuLi5bXX08L2Rpdj4)
[SWC](https://play.swc.rs/?version=1.3.100-nightly-20231124.1&code=H4sIAAAAAAAAA0vOzysuUUhUsFWwSckss6vW09OLjq210QdxAHOBudocAAAA&config=H4sIAAAAAAAAA1WOMQrDMAxF95zCaO5QPPY2wijFIbaDJENL8N0rO2lJN%2F33kPT3yTlYJMDD7TZa2JCF%2BJeNyDsrvowAhYQSOG4Kt69dpCvlSoO0Q8BaipCJGVehkyljlrlwul5nwqAX0FHNGlPfBqxaEmoMcOr290WRn6Sjmvi796NWm9oHTYlQ69cAAAA%3D)

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?
I am willing to add test code for this feature, but I need some help.
As I understand it, the test code should be placed in `test/snippets`, `test/snapshots`.
However, the `scripts/browser.js` that tests them does not seem to be able to execute properly.

2023-11-24 17:39 UTC, paperdave requested changes
can you add a test to transpiler.test.ts?

2023-11-24 17:40 UTC, paperdave commented
also, i wonder if we can detect an array literal spread, to emit `[1, 2, 3]` instead of `[...[1, 2, 3]]`

2023-11-27 02:04 UTC, rhyzx commented
> can you add a test to transpiler.test.ts?

DONE

2023-11-27 02:04 UTC, rhyzx commented
> also, i wonder if we can detect an array literal spread, to emit `[1, 2, 3]` instead of `[...[1, 2, 3]]`

Yes, the optimizer should do this, and actually Bun has already implemented this.

```js
// in.js
console.log([...[1, 2, 3]]);
console.log(
  jsxDEV(
    "div",
    {
      children: [...[1, 2, 3]],
    },
    undefined,
    true,
    undefined,
    this,
  ),
);
console.log(<div>{...[1, 2, 3]}</div>);

// bun-debug build test.js --minify
// ...
console.log([1,2,3]);
console.log(jsxDEV("div",{children:[1,2,3]},void 0,!0,void 0,OJ));
console.log(VJ.jsxDEV("div",{children:[...[1,2,3]]},void 0,!0,void 0,this))})
// ...
```

However, strangely, the code transformed through JSX does not execute this optimization.🤔

If I have time, I will attempt to fix this issue next.

2023-11-27 20:10 UTC, paperclover requested changes
looks good, i would like to get the `unreachable` removed.

2023-11-27 20:10 UTC, paperclover commented on src/js_parser.zig
> +                                        }) catch unreachable;
i know the old code had this but can you change `catch unreachable` to `catch bun.outOfMemory()`. the old code will behave weirdly in out of memory, where calling this new function will properly crash.

2023-11-27 20:10 UTC, paperclover commented
these test cases would be nice to have but dont pass right now. i dont really know how hard adding this optimization in would be.
```
expect(bun.transformSync("export var foo = <div>{...[1,2,3]}</div>")).toBe(
  `export var foo = jsxDEV("div", {
  children: [1, 2, 3]
}, undefined, true, undefined, this);
`,
);
expect(bun.transformSync("export var foo = <div>a{...[1,2,3]}b</div>")).toBe(
  `export var foo = jsxDEV("div", {
  children: [
    "a",
    1,
    2,
    3,
    "b"
  ]
}, undefined, true, undefined, this);
`,
);
```

2023-11-28 02:37 UTC, rhyzx commented on src/js_parser.zig
> +                                        }) catch unreachable;
DONE

2023-11-28 02:42 UTC, rhyzx commented
> these test cases would be nice to have but dont pass right now. i dont really know how hard adding this optimization in would be.
> 
> ```
> expect(bun.transformSync("export var foo = <div>{...[1,2,3]}</div>")).toBe(
>   `export var foo = jsxDEV("div", {
>   children: [1, 2, 3]
> }, undefined, true, undefined, this);
> `,
> );
> expect(bun.transformSync("export var foo = <div>a{...[1,2,3]}b</div>")).toBe(
>   `export var foo = jsxDEV("div", {
>   children: [
>     "a",
>     1,
>     2,
>     3,
>     "b"
>   ]
> }, undefined, true, undefined, this);
> `,
> );
> ```

I've observed that esbuild also doesn't optimize spread children in jsx, [see]( https://esbuild.github.io/try/#dAAwLjE5LjcAewogIGxvYWRlcjogJ2pzeCcsCiAganN4OiAnYXV0b21hdGljJywKICBtaW5pZnk6IHRydWUKfQBjb25zb2xlLmxvZyg8ZGl2PnsuLi5bMSwyXX08L2Rpdj4pCmNvbnNvbGUubG9nKFsuLi5bMSwyXV0pCmNvbnNvbGUubG9nKFsxLCAuLi5bMiwgM10sIDRdKQ)

Implementing this optimization may not be as easy as it seems. I think we should open a new issue to discuss it.

2023-11-28 02:50 UTC, paperdave approved these changes

2023-11-28 02:54 UTC, paperdave commented
alright. looks good otherwise. will merge after tests run.

2023-11-28 03:30 UTC, merged

2023-11-28 03:31 UTC, paperdave commented
thank you