test: init sharp integration test
oven-sh/bun pull request #7481
Opened 2023-12-06 02:53 UTC by ImBIOS

### What does this PR do?

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?

2023-12-06 04:16 UTC, paperdave commented
thank you. sharp used to be a harder package to run because it depended on postinstall (see #7132 for status on that) but these should pass now.

2023-12-06 04:20 UTC, paperdave requested changes
please cleanup the generated files from bun init. they are not needed. all that is needed is package.json, sharp.test.ts, bun.lockb, and bun.png

2023-12-06 04:20 UTC, paperdave commented on test/integration/sharp/.gitignore
> +# Based on https://raw.githubusercontent.com/github/gitignore/main/Node.gitignore
root of the entire project has a gitignore. please remove.

2023-12-06 04:20 UTC, paperdave commented on test/integration/sharp/README.md
> +# bun-integration-test-sharp
this file can also be 💥

2023-12-06 04:20 UTC, paperdave commented on test/integration/sharp/index.ts
> +console.log("Hello via Bun!");
💥

2023-12-06 04:20 UTC, paperdave commented on test/integration/sharp/package.json
> +    "postinstall": "cd node_modules/sharp && bun install/check.js"
this `postinstall` should be removed. if sharp doesnt work out of box then it is a bug in bun.

2023-12-06 04:20 UTC, paperdave commented on test/integration/sharp/tsconfig.json
> +{
💥

2023-12-06 05:05 UTC, ImBIOS commented
@paperdave updated, and I changed `postinstall` of sharp became `trustedDependencies`, is that correct?

2023-12-06 05:11 UTC, paperdave commented
Ideally this test should function without any configuration, no `trustedDependencies` set, but that might depend on the linked PR. I guess in the meantime it can be merged if it passes, and we will remove the trustedDependencies flag

2023-12-06 08:30 UTC, paperdave commented
doesnt pass now but we should be able to revisit these tests after postinstall branch merges and it hopefully will work as-is.

2023-12-06 08:39 UTC, dylan-conway commented on test/integration/sharp/sharp.test.ts
> +    const inputBuffer = await sharp("bun.png").resize(200, 200).toBuffer();
```suggestion
    const inputBuffer = await sharp(path.join(import.meta.dir, "bun.png")).resize(200, 200).toBuffer();
```
also for the other uses of `bun.png`

2023-12-06 08:40 UTC, dylan-conway commented
Thanks for these tests. I tested locally with the lifecycle script branch and they are passing

2023-12-06 08:41 UTC, dylan-conway commented on test/integration/sharp/package.json
> +    "sharp": "^0.33.0"
```suggestion
    "sharp": "0.33.0"
```

2023-12-06 11:32 UTC, ImBIOS commented
@dylan-conway @paperdave updated

2023-12-12 21:35 UTC, dylan-conway approved these changes

2023-12-12 21:35 UTC, merged

2023-12-12 21:35 UTC, dylan-conway commented
Thank you