Add -h as alias to --help
oven-sh/bun pull request #7519
Opened 2023-12-07 17:21 UTC by hustLer2k

### What does this PR do?

Implements https://github.com/oven-sh/bun/issues/7451.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

_**Existing tests pass and manual testing.**_

- [x] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I included a test for the new code, or an existing test covers it
- [x] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed
- [x] I wrote TypeScript/JavaScript tests and they pass locally (`bun-debug test test-file-name.test`)

2023-12-07 19:27 UTC, paperdave commented on src/cli.zig
> +        const print_help = args.flag("--help") or args.flag("-h");
did you check if the `or args.flag("-h")` is needed. i think clap is able to do this implicitly once you speicfy the -h alias  in the param list

2023-12-07 19:38 UTC, hustLer2k commented on src/cli.zig
> +        const print_help = args.flag("--help") or args.flag("-h");
it's actually not needed

2023-12-07 21:06 UTC, paperdave requested changes

2023-12-07 21:06 UTC, paperdave commented on src/cli.zig
> +                        if (strings.eqlComptime(arg, "--help") or strings.eqlComptime(arg, "-h")) {
unneeded

2023-12-07 21:06 UTC, paperclover commented on src/cli/init_command.zig
> +                if (strings.eqlComptime(arg, "--help") or strings.eqlComptime(arg, "-h")) {
unneeded x2

2023-12-07 21:06 UTC, paperclover commented
looks great besides hte unneeded ones

2023-12-11 22:55 UTC, paperdave approved these changes
looks great. will merge after tests

2023-12-12 00:27 UTC, merged