Add experimental nix support
oven-sh/bun pull request #76
Opened 2021-12-12 02:39 UTC by ajkachnic

As discussed in the discord, this PR adds experimental Nix support via a `default.nix` file and a small note in the README. While this is great and all, it still leaves many unanswered questions:

- Should we be building from source instead? (Currently unfeasible for multiple reasons, but good long term)
- How should we handle updating versions?
  - Should we just use the latest version at all times?
  - ~~Should use/update check-sums?~~ 
    As mentioned in the discord by @Jarred-Sumner 
    > There have been a couple cases where I had to re-upload the version after some build issue
    > so it might make sense to forgo the checksum for now
  - Should we dynamically update the `default.zig` file upon each new release with the `Makefile`?
- Should we provide more detailed instructions on how to install with Nix?
- When is the right time to submit to nixpkgs?
- How should we handle configuring Bun's cache directory?

*and the list goes on.*

There are definitely a few things that should be fixed here, this is a decent starting point to build upon.

2021-12-12 02:41 UTC, Jarred-Sumner commented on default.nix
> +  bun_install = "/home/<whatever>/.bun"; # Set this to where you want bun's cache
Would it be possible to fill this in with the current user's home directory instead of manually editing?

2021-12-12 02:44 UTC, Jarred-Sumner commented on README.md
> +There is a `default.nix` file bundled with Bun's source. This could eventually be brought to Nixpkgs, but for now, you can run and install it like any other nix package.
Would it be possible to pass a url to nix? If so, I could get the `default.nix` package up on bun.sh

2021-12-12 02:45 UTC, Jarred-Sumner approved these changes

2021-12-12 14:43 UTC, ajkachnic commented on default.nix
> +  bun_install = "/home/<whatever>/.bun"; # Set this to where you want bun's cache
It could be `$HOME/.bun`, I just forget if that will evaluate to the root's home directory or the user's (since the package might be built with superuser permissions). I'm pretty sure it's the user's though

2022-07-06 01:55 UTC, PureFunctor commented on default.nix
> +  bun_install = "/home/<whatever>/.bun"; # Set this to where you want bun's cache
`getEnv` can be used for this, I believe:
```suggestion
  bun_install = "{builtins.getEnv "HOME"}/.bun";
```
https://nixos.org/manual/nix/stable/expressions/builtins.html#builtins-getEnv

2022-07-06 19:49 UTC, Suyashtnt requested changes
Maybe add a flake.nix for flake users?

2022-07-09 18:49 UTC, lucasew commented
Related: https://github.com/NixOS/nixpkgs/pull/180299

2022-07-09 20:02 UTC, 06kellyjac commented on default.nix
> +  bun_install = "/home/<whatever>/.bun"; # Set this to where you want bun's cache
Just wrap with escaped $ so it evaluates when ran rather than in the build

2022-07-09 20:07 UTC, 06kellyjac commented on README.md
> +There is a `default.nix` file bundled with Bun's source. This could eventually be brought to Nixpkgs, but for now, you can run and install it like any other nix package.
You can build a remote expressions to an extent yeah

https://nixos.org/manual/nix/stable/command-ref/nix-build.html

With nix 3.0 & flakes you can easily do something like

`nix build github:Jarred-Summer/bun`
There's probably a way to set up a domain name but not played with it

2022-07-09 20:12 UTC, 06kellyjac commented
I think the main benefit of nix in this repo would be pulling in any missing dependencies in a nix dev shell

--

If we also want a package, copying the PR would be good. A source build is an option for the future.

As a note nixpkgs could never fetch nix files from this repo to add the package (that would be IFD (Import From Derivation))

For a reference of another project that offers a package/overlay neovim has some nix stuff in the contrib folder

2022-11-19 15:01 UTC, knarkzel commented
I have created a flake for getting the Bun binary here: [bun-flake](https://github.com/knarkzel/bun-flake). Feel free to steal it :smile:

2022-11-19 16:48 UTC, lucasew commented
> I have created a flake for getting the Bun binary here: [bun-flake](https://github.com/knarkzel/bun-flake). Feel free to steal it smile

Ty, just stole your code and added a bump script in our overlay

Every day at 6am it will verify automagically for new versions and bump 

https://github.com/nixosbrasil/nixpkgs-brasil/tree/master/pacotes/utilitarios/bun

2023-07-10 05:12 UTC, koalazub commented
Hey! Just wanting to bump this and to see if there's been any headway in being able to openly support nix builds using flakes? I would attempt it myself, but I'm not experienced enough with nixos as yet

I can see that the package is available on search.nixos.org. But only from version `0.6.2` and not as a flake

2023-07-16 18:57 UTC, lucasew commented
> Hey! Just wanting to bump this and to see if there's been any headway in being able to openly support nix builds using flakes? I would attempt it myself, but I'm not experienced enough with nixos as yet
> 
> I can see that the package is available on search.nixos.org. But only from version `0.6.2` and not as a flake

We have bun packaged in binary form in our community overlay

It's updated every night

https://github.com/nixosbrasil/nixpkgs-brasil

2023-07-20 01:47 UTC, koalazub commented
> > Hey! Just wanting to bump this and to see if there's been any headway in being able to openly support nix builds using flakes? I would attempt it myself, but I'm not experienced enough with nixos as yet
> 
> > 
> 
> > I can see that the package is available on search.nixos.org. But only from version `0.6.2` and not as a flake
> 
> 
> 
> We have bun packaged in binary form in our community overlay
> 
> 
> 
> It's updated every night
> 
> 
> 
> https://github.com/nixosbrasil/nixpkgs-brasil

I was kind of confused about the whole discussion as it's not a release that stems from the `oven-sh` organisation. So I wasn't sure if that was an official package. On top of that, I'm very new to nix and so I was trying to figure out how to install the latest version of it. 

I forgot to document on here, but I was able to install the latest version of bun using unstable-nix.pkg and not just nixpkg. 

An example of my [configuration.nix](https://gist.github.com/koalazub/d94d6b591d28a2aedfc0e298623e853f) in case anyone else is still getting their bearings

2023-07-31 13:39 UTC, closed without merging