feat: add `toBeObject`
oven-sh/bun pull request #7770
Opened 2023-12-21 16:31 UTC by coratgerl

### What does this PR do?

Add `toBeObject` from https://github.com/oven-sh/bun/issues/1825

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

 I wrote automated tests

- [x] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I included a test for the new code, or an existing test covers it
- [x] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed
- [x] I wrote TypeScript/JavaScript tests and they pass locally (`bun-debug test test-file-name.test`)

2023-12-21 16:35 UTC, Electroid requested changes

2023-12-21 16:35 UTC, Electroid commented on test/js/bun/test/expect.test.js
> +  test("toBeObject()", () => {
Could we add some more test cases here? e.g. `class A {}`, `[]`, `new Set()`, etc

2023-12-21 16:35 UTC, Electroid commented on src/bun.js/test/expect.zig
> +        active_test_expectation_counter.actual += 1;
```suggestion
        incrementExpectCallCounter();
```

2023-12-21 16:39 UTC, coratgerl commented on test/js/bun/test/expect.test.js
> +  test("toBeObject()", () => {
Yes of course, it's added !

2023-12-21 16:43 UTC, Electroid commented
Thanks for working on this! Looks good, running the test suite now, and will have 1 other person review.

2023-12-22 08:41 UTC, dylan-conway commented on src/bun.js/test/expect.zig
> +            const fmt = comptime getSignature("toBeObject", "", true) ++ "\n\n" ++ "Received: <red>{any}<r>\n";
could you add in a line above `Received: ...` that says `Expected value to be an object\n\n`? Similar to the formatting in `toBeEmpty`

2023-12-22 08:41 UTC, dylan-conway commented on src/bun.js/test/expect.zig
> +        const fmt = comptime getSignature("toBeObject", "", false) ++ "\n\n" ++ "Received: <red>{any}<r>\n";
same here

2023-12-29 20:36 UTC, dylan-conway approved these changes
Thank you

2023-12-29 20:37 UTC, merged