feat(server): add server backlog parameter
oven-sh/bun pull request #7822
Opened 2023-12-25 06:36 UTC by Hanaasagi

### What does this PR do?

This pull request adds the `backlog` parameter to both `Bun.listen` and `Bun.serve`. Additionally, it addresses the issue where the `backlog` parameter of the` server.listen` function on the Node.js side was not taking effect. The default value is `512`.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

passed existing tests. And manually tested.

##### `Bun.serve`

```JavaScript
Bun.serve({
  hostname: "127.0.0.1",
  port: 8080,
  backlog: 1024,
  fetch(request) {
    console.log(request.url);
  },
});
```

##### `Bun.listen`

```JavaScript
Bun.listen({
  hostname: "127.0.0.1",
  port: 8080,
  backlog: 1024,
  socket: {
    data(socket, data) { },
  },
});
```

##### `http.createServer`

```JavaScript
const http = require("http");

const server = http.createServer((req, res) => {});
server.listen(8080, "127.0.0.1", 1024, () => {
  console.log("opened server on", server.address());
});

```

##### `net.createServer`

```JavaScript
const net = require("net");
const server = net.createServer();

server.listen(8080, "127.0.0.1", 1024, () => {
  console.log("opened server on", server.address());
});
```

Run the above code and see `send-q` via `ss` command

```
>> ss -tuln | grep 8080
tcp   LISTEN 0      2048       127.0.0.1:8080       0.0.0.0:*
```

2023-12-26 12:46 UTC, Hanaasagi commented
I noticed that the Ubuntu action image has the `ss` command, so I added unit tests.

2023-12-26 17:38 UTC, cirospaciari requested changes
nice, LGTM only thing that I can see is 511 instead of 512 for backlog default to match nodejs implementation.

Will check the CI/CD tests after these changes.

2023-12-26 17:38 UTC, cirospaciari commented on src/js/node/net.js
> +      onListen = backlog;
```suggestion
      onListen = backlog;
      backlog = undefined;
```

2023-12-26 17:38 UTC, cirospaciari commented on src/bun.js/api/bun/socket.zig
> +        var backlog: i32 = 512;
```suggestion
        var backlog: i32 = 511;
```

2023-12-26 17:38 UTC, cirospaciari commented on src/bun.js/api/bun/socket.zig
> +    backlog: i32 = 512,
```suggestion
    backlog: i32 = 511,
```

2023-12-26 17:38 UTC, cirospaciari commented on src/bun.js/api/bun/socket.zig
> +    backlog: i32 = 512,
https://nodejs.org/api/net.html#serverlisten default value is actually 511

2023-12-26 17:38 UTC, cirospaciari commented on packages/bun-types/bun.d.ts
> +     * @default 512
```suggestion
     * @default 511
```

2023-12-28 17:19 UTC, cirospaciari approved these changes

2023-12-28 17:19 UTC, merged

2023-12-28 17:19 UTC, cirospaciari commented
Thank you!