Fixes #7001
oven-sh/bun pull request #7861
Opened 2023-12-27 08:46 UTC by Jarred-Sumner

### What does this PR do?

This fixes the immediate cause of #7001. It doesn't fix it in every case (such as streams)

1) Makes it so `ReadableStream.prototype.isLocked` returns true if our hidden native pointer value is set to `-1`. 
2) We check if the `ReadableStream` is locked, including for Blob values

### How did you verify your code works?

There are some tests

@cirospaciari please review this closely because it's very easy to subtly break things with this code and I'm worried something will break due to this change

2023-12-27 08:49 UTC, Jarred-Sumner commented on src/bun.js/webcore/streams.zig
> +        stream.reloadTag(globalThis);
This is the main cause 

We internally store the `ReadableStream` on the `PendingValue`, and the pointer becomes stale. It is a use-after-free where the `ptr` has been detached, but the existing `PendingValue` hasn't been updated to reflect that. To address this, we reload the tag.

2023-12-27 08:50 UTC, Jarred-Sumner commented on src/bun.js/webcore/streams.zig
> +        this.value.unprotect();
Moving this after out of caution that the value gets GC'd immediately after its unprotected

2023-12-27 08:51 UTC, Jarred-Sumner commented on src/js/builtins/ReadableStreamInternals.ts
> +  $assert(
This fixes the debug assertion failure in the direct readable stream tests.

2023-12-27 19:59 UTC, cirospaciari commented on src/bun.js/webcore/response.zig
> +                            if (stream.isDisturbed(globalThis)) {
should we also check isDisturbed in other places we call `useAsAnyBlob`? like: https://github.com/oven-sh/bun/blob/99aef8c217c783d5a23ed5911dca77678b6f1bde/src/bun.js/webcore/response.zig#L1996 https://github.com/oven-sh/bun/blob/99aef8c217c783d5a23ed5911dca77678b6f1bde/src/bun.js/webcore/response.zig#L1779

2023-12-27 19:59 UTC, cirospaciari commented on src/js/node/stream.js
> +      if (ptr === 0 || ptr === -1) {
maybe adding some comments for what -1 and 0 mean (Locked/Detached) so we can remember next time

2023-12-27 20:27 UTC, cirospaciari commented on test/regression/issue/07740.test.ts
> +it("duplicate dependencies should warn instead of error", () => {
this test fails on linux

2024-01-03 16:08 UTC, cirospaciari requested changes
tests failures

2024-01-12 00:25 UTC, merged