Added Wget cli utility for easier download.
oven-sh/bun pull request #795
Opened 2022-07-20 05:48 UTC by abhaytaras7

As we know ** curl** and ** wget ** are the most popular download tools . very few people are familiar with ** curl ** commands.

Adding ** wget** into this project will help them installing ** bun** more easier 🙂

2022-07-20 14:28 UTC, Toby222 commented
you forgot to add
```sh
chmod +x ./install
./install
```

2022-07-20 17:45 UTC, abhaytaras7 commented
> you forgot to add
> 
> ```shell
> chmod +x ./install
> ./install
> ```
 wont this be user's choice >?

2022-07-21 12:45 UTC, Toby222 commented
> wont this be user's choice >?
This section is about how to install bun. So no, the instructions on how to actually install bun are not a choice at this point.

2022-07-22 09:57 UTC, abhaytaras7 commented
> Made the necessary changes

2022-07-25 20:51 UTC, xHyroM requested changes

2022-07-25 20:51 UTC, xHyroM commented on README.md
> +
why 3 codeblocks?
```suggestion
```sh
wget https://bun.sh/install
chmod a+x ./install
./install
```
```

2022-07-28 06:45 UTC, kidonng commented
Why not just pipe like `wget -qO- https://bun.sh/install | bash`?

2022-07-28 07:05 UTC, Toby222 commented
> Why not just pipe like `wget -qO- https://bun.sh/install | bash`?

Why not just pipe like `curl -SLlf https://bun.sh/install | bash`? :^)

2022-07-28 07:51 UTC, kidonng commented
@Toby222 This is already mentioned in the README, while I'm suggesting a change to the pull request.

2022-07-28 08:23 UTC, Toby222 commented
> @Toby222 This is already mentioned in the README, while I'm suggesting a change to the pull request.

Was meant moer as a joke, I get that it's possibly.
But by also, the point you get to using wget to print to stdout, why would you still use wget? I'm not aware of a system that has wget but not curl.

2022-07-28 09:41 UTC, xHyroM requested changes

2022-07-28 09:41 UTC, xHyroM commented on README.md
> +```
````suggestion
```sh
wget -qO- https://bun.sh/install | bash
```
````

2022-07-28 11:39 UTC, kidonng commented
> But by also, the point you get to using wget to print to stdout, why would you still use wget? I'm not aware of a system that has wget but not curl.

I agree with you, but I'm not the author and can only suggest something better.

2022-08-07 20:03 UTC, Jarred-Sumner commented
I think showing multiple options is confusing and instead Bun should have packages for different package managers

2022-08-07 20:03 UTC, closed without merging