Setup clang-tidy (C++ linter)
oven-sh/bun pull request #7961
Opened 2024-01-03 07:50 UTC by Jarred-Sumner

### What does this PR do?

This adds clang-tidy which is a very slow C++ linter. It is slow because it first compiles all the C++ code, and then lints it.

### How did you verify your code works?

Lets see what CI says

2024-01-03 13:00 UTC, alex-demchenko commented
Hi! Also PVS-Studio (static code analyzer) is pretty good. For example its used in Unreal Engine.

2024-01-03 22:39 UTC, Electroid commented on .github/workflows/bun-release.yml
> +        run: apt update && apt install -y llvm-16-dev libclang-16-dev clang-16 libssl-dev libxml2-dev build-essential ninja-build cmake
Edited wrong file?

2024-01-05 18:47 UTC, paperdave commented
why are you passing NO_CODEGEN?

this build:lint script doesnt run locally and it doesnt even work in ci

2024-01-05 19:22 UTC, paperdave commented
I have pushed a commit to make this actually run the build, but there are failing lints. some are very suspicious.

2024-01-18 04:53 UTC, jdalton commented on src/bun.js/bindings/BunPlugin.cpp
> +    // JSFunction* setupFunction = jsCast<JSFunction*>(setupFunctionValue);
Debug code ☝️ ?

2024-01-18 04:53 UTC, jdalton commented on src/bun.js/bindings/BunProcess.cpp
> -    auto clientData = WebCore::clientData(vm);
Yes removal of unused vars :DDD

2024-01-18 04:54 UTC, jdalton commented
💪 I dig this

2024-02-13 19:02 UTC, paperdave requested changes
putting a request changes to get this out of my inbox

issues with this as i remember a month ago are mainly that it does not solve all exposed warnings (will just be an annoyance to CI that is never paid attention to if it is always red)

2024-05-16 03:35 UTC, merged