implemented assert.doesNotMatch
oven-sh/bun pull request #8008
Opened 2024-01-05 23:34 UTC by markusn

### What does this PR do?

It implements assert.doesNotMatch making node:assert fully implemented.

_The documentation and TypeScript definitions already exists, this just provides the missing implementation._

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

I wrote automated tests.

If JavaScript/TypeScript modules or builtins changed:

- [x] I included a test for the new code, or existing tests cover it
- [x] I ran my tests locally and they pass (`bun-debug test test-file-name.test`)

If new methods, getters, or setters were added to a publicly exposed class:

_The documentation and TypeScript definitions already exists, this just provides the missing implementation._

- [ ] I added TypeScript types for the new methods, getters, or setters

2024-01-08 12:09 UTC, markusn commented
@Jarred-Sumner I've looked at the failing tests and they seem unrelated to the changes in this PR.

2024-01-08 20:07 UTC, paperdave requested changes

2024-01-08 20:07 UTC, paperclover commented on test/js/node/assert/assert-doesNotMatch.test.cjs
> +  } catch (e) {}
check that the type of error thrown here is not an expect unreachable error

2024-01-08 20:07 UTC, paperclover commented on test/js/node/assert/assert-doesNotMatch.test.cjs
> +  } catch (e) {}
check error

2024-01-08 20:08 UTC, paperdave commented
i apologize, these review comments were written weeks ago but i hadnt pressed submit

2024-01-08 21:00 UTC, markusn commented on test/js/node/assert/assert-doesNotMatch.test.cjs
> +  } catch (e) {}
thanks for the comment, this actually highlighted an actual problem with the code

2024-01-08 21:00 UTC, markusn commented on test/js/node/assert/assert-doesNotMatch.test.cjs
> +  } catch (e) {}
thanks for the comment, this actually highlighted an actual problem with the code

2024-01-08 21:00 UTC, markusn commented
> i apologize, these review comments were written days ago but i hadnt pressed submit

No problem, I've changed the tests to expect the error instead.

2024-01-08 22:38 UTC, paperdave approved these changes

2024-01-09 01:31 UTC, merged

2024-01-09 01:31 UTC, paperclover commented
thank you