Update contributing.md
oven-sh/bun pull request #8014
Opened 2024-01-06 06:24 UTC by karmabadger

Added documentation for the installation of the perl Math::BigInt module

### What does this PR do?

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?

2024-01-06 06:25 UTC, karmabadger commented
This is what I had to run on Fedora 38 in order to get the `bun setup` command to work

2024-01-06 06:25 UTC, Jarred-Sumner commented on docs/project/contributing.md
> +{% /codetabs %}
Is this intentional?

2024-01-06 06:27 UTC, paperdave requested changes
instead of the extra notes, just add the new package name to the fedora install command

2024-01-06 06:29 UTC, karmabadger commented
@Jarred-Sumner @paperdave you're totally right, I forgot it was literally from dnf as well and can be added to the same command. Let me fix that

2024-01-06 06:38 UTC, karmabadger commented
@Jarred-Sumner @paperdave should be fixed now

2024-01-06 06:38 UTC, karmabadger commented on docs/project/contributing.md
> +{% /codetabs %}
no haha my bad

2024-01-08 22:41 UTC, paperdave approved these changes

2024-01-08 22:42 UTC, merged