Fix #8090
oven-sh/bun pull request #8142
Opened 2024-01-13 01:50 UTC by Aarav-Juneja

### What does this PR do?

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

My new test started passing and no other tests started failing.

I am a new developer to open source. Please tell me if anything is wrong and I need to fix anything.

2024-01-13 02:09 UTC, paperdave approved these changes

2024-01-13 02:15 UTC, paperdave commented
Fixes #8090

2024-01-13 04:03 UTC, paperdave requested changes
there are failing tests

https://github.com/oven-sh/bun/actions/runs/7509482444?pr=8142

path.test.js is the one of note.

2024-01-14 20:34 UTC, Aarav-Juneja commented
I have fixed the issue and it now passes tests.
<img width="430" alt="Screenshot 2024-01-14 at 12 33 52 PM" src="https://github.com/oven-sh/bun/assets/61629581/03d5df4e-eb30-470d-b9f8-fc77be6a5803">

2024-01-16 22:11 UTC, paperdave approved these changes

2024-01-16 22:12 UTC, merged