feat: Carry over node isIPv4/isIPv6 performance improvements
oven-sh/bun pull request #8271
Opened 2024-01-19 02:16 UTC by maxmilton

### What does this PR do?

Copy over the `isIPv4`/`isIPv6` performance improvements from
<https://github.com/nodejs/node/pull/49568>.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ x] Code changes

### How did you verify your code works?

Run relevant tests:
- `./build/bun-debug test test/js/bun/dns`
- `./build/bun-debug test test/js/node/net/`

2024-01-19 03:41 UTC, Jarred-Sumner requested changes
JavaScriptCore is a different engine, so the performance may be different. Do you have a benchmark that shows this regex is faster than the previous?

2024-01-19 10:16 UTC, maxmilton commented
Sure, that makes sense, since the regex engine is likely to be quite different. The new code is also faster in bun except for some specific cases.

<details>
<summary>Here are mitata based benchmarks:</summary>

```js
import { baseline, bench, group, run } from 'mitata';
import assert from 'node:assert';

const v4Seg_OLD = '(?:[0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])';
const v4Str_OLD = `(${v4Seg_OLD}[.]){3}${v4Seg_OLD}`;
const IPv4Reg_OLD = new RegExp(`^${v4Str_OLD}$`);

const v6Seg_OLD = '(?:[0-9a-fA-F]{1,4})';
const IPv6Reg_OLD = new RegExp(
  '^(' +
    `(?:${v6Seg_OLD}:){7}(?:${v6Seg_OLD}|:)|` +
    `(?:${v6Seg_OLD}:){6}(?:${v4Str_OLD}|:${v6Seg_OLD}|:)|` +
    `(?:${v6Seg_OLD}:){5}(?::${v4Str_OLD}|(:${v6Seg_OLD}){1,2}|:)|` +
    `(?:${v6Seg_OLD}:){4}(?:(:${v6Seg_OLD}){0,1}:${v4Str_OLD}|(:${v6Seg_OLD}){1,3}|:)|` +
    `(?:${v6Seg_OLD}:){3}(?:(:${v6Seg_OLD}){0,2}:${v4Str_OLD}|(:${v6Seg_OLD}){1,4}|:)|` +
    `(?:${v6Seg_OLD}:){2}(?:(:${v6Seg_OLD}){0,3}:${v4Str_OLD}|(:${v6Seg_OLD}){1,5}|:)|` +
    `(?:${v6Seg_OLD}:){1}(?:(:${v6Seg_OLD}){0,4}:${v4Str_OLD}|(:${v6Seg_OLD}){1,6}|:)|` +
    `(?::((?::${v6Seg_OLD}){0,5}:${v4Str_OLD}|(?::${v6Seg_OLD}){1,7}|:))` +
    ')(%[0-9a-zA-Z-.:]{1,})?$',
);

function isIPv4_OLD(s) {
  return IPv4Reg_OLD.test(s);
}
function isIPv6_OLD(s) {
  return IPv6Reg_OLD.test(s);
}
function isIP_OLD(s) {
  if (isIPv4_OLD(s)) return 4;
  if (isIPv6_OLD(s)) return 6;
  return 0;
}

const v4Seg_NEW = '(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])';
const v4Str_NEW = `(?:${v4Seg_NEW}\\.){3}${v4Seg_NEW}`;
const IPv4Reg_NEW = new RegExp(`^${v4Str_NEW}$`);

const v6Seg_NEW = '(?:[0-9a-fA-F]{1,4})';
const IPv6Reg2_NEW = new RegExp(
  '^(?:' +
    `(?:${v6Seg_NEW}:){7}(?:${v6Seg_NEW}|:)|` +
    `(?:${v6Seg_NEW}:){6}(?:${v4Str_NEW}|:${v6Seg_NEW}|:)|` +
    `(?:${v6Seg_NEW}:){5}(?::${v4Str_NEW}|(?::${v6Seg_NEW}){1,2}|:)|` +
    `(?:${v6Seg_NEW}:){4}(?:(?::${v6Seg_NEW}){0,1}:${v4Str_NEW}|(?::${v6Seg_NEW}){1,3}|:)|` +
    `(?:${v6Seg_NEW}:){3}(?:(?::${v6Seg_NEW}){0,2}:${v4Str_NEW}|(?::${v6Seg_NEW}){1,4}|:)|` +
    `(?:${v6Seg_NEW}:){2}(?:(?::${v6Seg_NEW}){0,3}:${v4Str_NEW}|(?::${v6Seg_NEW}){1,5}|:)|` +
    `(?:${v6Seg_NEW}:){1}(?:(?::${v6Seg_NEW}){0,4}:${v4Str_NEW}|(?::${v6Seg_NEW}){1,6}|:)|` +
    `(?::(?:(?::${v6Seg_NEW}){0,5}:${v4Str_NEW}|(?::${v6Seg_NEW}){1,7}|:))` +
    ')(?:%[0-9a-zA-Z-.:]{1,})?$',
);

function isIPv4_NEW(s) {
  return IPv4Reg_NEW.test(s);
}
function isIPv6_NEW(s) {
  return IPv6Reg2_NEW.test(s);
}
function isIP_NEW(s) {
  if (isIPv4_NEW(s)) return 4;
  if (isIPv6_NEW(s)) return 6;
  return 0;
}

const v4_ips = [
  '0.0.0.0',
  '127.0.0.1',
  '255.255.255.255',
  '192.168.0.1',
  '192.0.2.33',
];
const v6_ips = [
  '::1',
  'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
  '2001:db8:85a3:0:0:8a2e:370:7334',
  '::ffff:192.0.2.33',
];
const invalid_ips = [
  '',
  '.',
  '0.0.0',
  '10.168.209.250.1',
  'ffff:ffff:ffff:ffff:ffff:ffff:ffff:fffg',
];

baseline('baseline', () => 0); // prevent some first run bias

group('isIPv4 true', () => {
  for (const ip of v4_ips) {
    assert.ok(isIPv4_NEW(ip));
    assert.ok(isIPv4_OLD(ip));
    bench(`NEW ${ip}`, () => isIPv4_NEW(ip));
    bench(`OLD ${ip}`, () => isIPv4_OLD(ip));
  }
});

group('isIPv4 false', () => {
  for (const ip of [...v6_ips, ...invalid_ips]) {
    assert.ok(!isIPv4_NEW(ip));
    assert.ok(!isIPv4_OLD(ip));
    bench(`OLD ${ip}`, () => isIPv4_OLD(ip));
    bench(`NEW ${ip}`, () => isIPv4_NEW(ip));
  }
});

group('isIPv6 true', () => {
  for (const ip of v6_ips) {
    assert.ok(isIPv6_NEW(ip));
    assert.ok(isIPv6_OLD(ip));
    bench(`NEW ${ip}`, () => isIPv6_NEW(ip));
    bench(`OLD ${ip}`, () => isIPv6_OLD(ip));
  }
});

group('isIPv6 false', () => {
  for (const ip of [...v4_ips, ...invalid_ips]) {
    assert.ok(!isIPv6_NEW(ip));
    assert.ok(!isIPv6_OLD(ip));
    bench(`OLD ${ip}`, () => isIPv6_OLD(ip));
    bench(`NEW ${ip}`, () => isIPv6_NEW(ip));
  }
});

group('isIP true', () => {
  for (const ip of v4_ips) {
    assert.strictEqual(isIP_NEW(ip), 4);
    assert.strictEqual(isIP_OLD(ip), 4);
    bench(`NEW ${ip}`, () => isIP_NEW(ip));
    bench(`OLD ${ip}`, () => isIP_OLD(ip));
  }
  for (const ip of v6_ips) {
    assert.strictEqual(isIP_NEW(ip), 6);
    assert.strictEqual(isIP_OLD(ip), 6);
    bench(`NEW ${ip}`, () => isIP_NEW(ip));
    bench(`OLD ${ip}`, () => isIP_OLD(ip));
  }
});

group('isIP false', () => {
  for (const ip of invalid_ips) {
    assert.strictEqual(isIP_NEW(ip), 0);
    assert.strictEqual(isIP_OLD(ip), 0);
    bench(`NEW ${ip}`, () => isIP_NEW(ip));
    bench(`OLD ${ip}`, () => isIP_OLD(ip));
  }
});

await run();
```

</details>

<details>
<summary>And the mitata results:</summary>

```
❱ bun ./isip-regex.mjs
cpu: AMD Ryzen 7 7735HS with Radeon Graphics
runtime: bun 1.0.23 (x64-linux)

benchmark                                        time (avg)             (min … max)       p75       p99      p995
----------------------------------------------------------------------------------- -----------------------------
baseline                                     423.88 ps/iter   (418.7 ps … 14.47 ns)  419.8 ps  439.8 ps  573.1 ps

summary
  baseline

• isIPv4 true
----------------------------------------------------------------------------------- -----------------------------
NEW 0.0.0.0                                  192.26 ns/iter (191.02 ns … 197.67 ns) 192.32 ns 196.52 ns 196.58 ns
OLD 0.0.0.0                                  129.38 ns/iter (128.13 ns … 133.46 ns)  129.5 ns 132.66 ns 132.93 ns
NEW 127.0.0.1                                193.82 ns/iter (193.01 ns … 198.26 ns) 193.89 ns 197.73 ns 197.99 ns
OLD 127.0.0.1                                187.35 ns/iter (180.63 ns … 218.25 ns) 187.81 ns 204.93 ns 214.89 ns
NEW 255.255.255.255                          132.72 ns/iter (131.59 ns … 183.88 ns) 132.49 ns 138.58 ns 138.77 ns
OLD 255.255.255.255                          427.16 ns/iter (420.43 ns … 435.97 ns)    428 ns 435.26 ns 435.97 ns
NEW 192.168.0.1                              177.64 ns/iter (175.41 ns … 246.14 ns) 177.36 ns 185.63 ns 219.55 ns
OLD 192.168.0.1                              250.84 ns/iter (241.19 ns … 269.38 ns) 252.78 ns 267.34 ns  268.1 ns
NEW 192.0.2.33                               208.01 ns/iter (205.78 ns … 254.43 ns) 207.96 ns 214.57 ns 215.11 ns
OLD 192.0.2.33                               214.24 ns/iter (209.95 ns … 222.26 ns)  214.9 ns 219.57 ns 220.61 ns

summary for isIPv4 true
  OLD 0.0.0.0
   1.03x faster than NEW 255.255.255.255
   1.37x faster than NEW 192.168.0.1
   1.45x faster than OLD 127.0.0.1
   1.49x faster than NEW 0.0.0.0
   1.5x faster than NEW 127.0.0.1
   1.61x faster than NEW 192.0.2.33
   1.66x faster than OLD 192.0.2.33
   1.94x faster than OLD 192.168.0.1
   3.3x faster than OLD 255.255.255.255

• isIPv4 false
----------------------------------------------------------------------------------- -----------------------------
OLD ::1                                       84.53 ns/iter   (82.96 ns … 97.57 ns)  85.02 ns  88.94 ns  89.62 ns
NEW ::1                                       88.92 ns/iter      (88 ns … 91.75 ns)  88.91 ns  90.71 ns  90.96 ns
OLD ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  341.36 ns/iter  (339.2 ns … 347.96 ns) 342.65 ns 346.95 ns 347.96 ns
NEW ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  348.46 ns/iter (347.25 ns … 356.42 ns) 348.34 ns 355.89 ns 356.42 ns
OLD 2001:db8:85a3:0:0:8a2e:370:7334          339.25 ns/iter (335.65 ns … 346.99 ns) 339.95 ns 346.75 ns 346.99 ns
NEW 2001:db8:85a3:0:0:8a2e:370:7334          344.55 ns/iter (343.12 ns … 358.76 ns) 344.39 ns 351.23 ns 358.76 ns
OLD ::ffff:192.0.2.33                        192.41 ns/iter  (189.3 ns … 196.81 ns) 193.01 ns 196.33 ns 196.61 ns
NEW ::ffff:192.0.2.33                        207.94 ns/iter (206.34 ns … 212.66 ns) 208.09 ns 211.69 ns 211.98 ns
OLD                                           23.18 ns/iter   (22.46 ns … 31.46 ns)   23.2 ns  23.75 ns  24.14 ns
NEW                                    [...]

2024-01-19 22:27 UTC, dsonet commented
Since the changes were making the capturing group to be non-capturing, I suppose it would also use less memory?

2024-01-20 01:31 UTC, Jarred-Sumner commented
Awesome. Thank you .

2024-01-20 01:31 UTC, merged

2024-01-22 00:35 UTC, Uzlopak commented
@Jarred-Sumner 

Well... #4691

This will not motivate people to participate...

2024-01-22 20:39 UTC, maxmilton commented
@Uzlopak sorry, that's my bad. I did look for an existing issue but it seems I didn't search through the existing PRs!