chore: add types for Jest's date mocking API
oven-sh/bun pull request #8387
Opened 2024-01-23 02:54 UTC by DaleSeo

### What does this PR do?

This pull request adds types for Jest's date mocking API. It will assist in existing tests that utilize `setSystemTime`, `useFakeTimers`, and `useRealTimers`.

![Shot 2024-01-22 at 21 52 08@2x](https://github.com/oven-sh/bun/assets/5466341/0b47169d-6cec-45fc-b8d0-9cf638179de6)

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

2024-01-23 02:55 UTC, Jarred-Sumner commented on packages/bun-types/test.d.ts
> +    useRealTimers(): typeof jest;
we have not implemented this

2024-01-23 02:55 UTC, Jarred-Sumner commented on packages/bun-types/test.d.ts
> +    useFakeTimers(): typeof jest;
we have not implemented this

2024-01-23 02:55 UTC, Jarred-Sumner commented on packages/bun-types/test.d.ts
> +    setSystemTime(now?: number | Date): void;
we have implemented this

2024-01-23 02:55 UTC, Jarred-Sumner requested changes
only the `setSystemTime` one for now

2024-01-23 02:58 UTC, DaleSeo commented
@Jarred-Sumner I was under the impression that they are all supported after reding the docs below.

![Shot 2024-01-22 at 21 56 38@2x](https://github.com/oven-sh/bun/assets/5466341/64318bd2-c766-403e-82c8-932a922ae087)

https://bun.sh/docs/test/time#setsystemtime

2024-01-23 02:59 UTC, DaleSeo commented
> only the `setSystemTime` one for now

@Jarred-Sumner Removed `setSystemTime` and `useFakeTimers`.

2024-01-28 17:42 UTC, DaleSeo commented
@Jarred-Sumner Could you please take another look at this PR?

2024-02-17 16:05 UTC, Electroid approved these changes
Thanks!

2024-02-17 16:05 UTC, merged