[windows] non-blocking TransmitFile
oven-sh/bun pull request #8459
Opened 2024-01-24 19:05 UTC by cirospaciari

### What does this PR do?

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

Existing Tests

2024-01-24 20:31 UTC, jdalton commented on src/bun.js/api/server.zig
> +    transmitFileContext: if (Environment.isWindows) ?bun.windows.TransmitFileContext else u0 = if (Environment.isWindows) null else 0,
This chained ternary-ish-conditional is hard to parse mentally. It looks like the `else` side of `if (Environment.isWindows)` so the `false` side also has a check for `if (Environment.isWindows)`.

2024-01-24 20:33 UTC, jdalton commented on src/bun.js/api/server.zig
> +                    this.sendfile.transmitFileContext = bun.windows.TransmitFileContext.init();
We have a `bun.windows` and ` bun.win32` struct which is confusing.

2024-01-25 03:41 UTC, Jarred-Sumner requested changes
fetch tests are failing

2024-01-26 09:02 UTC, Jarred-Sumner commented
@cirospaciari which tests are now passing because of this PR?

2024-02-19 18:23 UTC, closed without merging