Fix for #8729
oven-sh/bun pull request #8739
Opened 2024-02-06 23:45 UTC by akash-melachuri

### What does this PR do?

This fixes #8729 by returning `success = false` from `Bun.spawnSync`. It goes down the already existing execution path that returns a `SystemError` in `node:child_process` since I didn't know how to return the error code/information from `Bun.spawnSync` cleanly without changing the API of `Bun.spawnSync`.

After this change, the following:
```
const { spawnSync } = require("child_process");

console.log(spawnSync("doesnotexist"));
```

Results in:
```
{
  signal: null,
  status: undefined,
  output: [ null, null, null ],
  stdout: null,
  stderr: null,
  error: 1 | const { spawnSync } = require("child_process");
2 | 
3 | console.log(spawnSync("doesnotexist"));
                ^
error: null
   errno: -1
   code: "undefined"
 syscall: "spawnSync"
   path: "doesnotexist"

      at new SystemError (node:child_process:1094:27)
      at node:child_process:247:49
      at /home/akash/Dev/bun/script.js:3:13
      at asyncFunctionResume (:1:21)
      at promiseReactionJobWithoutPromiseUnwrapAsyncContext (:1:21)
      at promiseReactionJob (:1:21)
,
}
```

This is my first issue/pull request, so I'd appreciate any advice or guidance.

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [x] Code changes

### How did you verify your code works?

I wrote a test and verified locally it passes

2024-02-06 23:52 UTC, Electroid requested changes

2024-02-06 23:52 UTC, Electroid commented on test/js/bun/spawn/spawn.test.ts
> +        const { success } = spawnSync({
This also needs to test that an `error` is defined and matches an Error

2024-02-08 19:46 UTC, gvilums commented
We currently have some big changes to subprocess spawning coming up (should get merged by tomorrow). I think it makes sense to wait for those to land and then see how to apply the fix from this PR.

2024-04-21 16:26 UTC, prabhu commented
@gvilums any updates? #8729 is blocking one of my project.

2024-04-22 16:18 UTC, gvilums commented
> @gvilums any updates? #8729 is blocking one of my project.

I'll look into it, will have to port over the changes from this PR to the new version, but that shouldn't be too difficult

2025-01-09 12:46 UTC, closed without merging

2025-01-09 12:46 UTC, RiskyMH commented
Superseded by #15561