Fix #8817
oven-sh/bun pull request #8847
Opened 2024-02-11 01:52 UTC by zackradisic

### What does this PR do?

Fixes #8817, the issue was properly applying the wildcard-filepath optimization. I added tests to make sure its used properly

2024-02-11 03:31 UTC, Jarred-Sumner requested changes
Shell leak test is failing

2024-02-14 06:27 UTC, Jarred-Sumner commented
there are merge conflicts

2024-02-15 06:41 UTC, Jarred-Sumner commented
74 failing scan tests

2024-02-15 06:42 UTC, Jarred-Sumner requested changes
Test failures

2024-02-16 00:35 UTC, jdalton commented on src/glob.zig
> +                this.debugPatternComopnents();
☝️ Does this make a pretty debug log?

2024-02-16 00:36 UTC, jdalton commented on src/glob.zig
>                                  else => {},
Love the code comments here ❤️

2024-02-16 00:38 UTC, jdalton commented on src/glob.zig
> +                var path_buf: *[bun.MAX_PATH_BYTES]u8 = &this.walker.pathBuf;
```suggestion
                var path_buf: *bun.PathBuffer = &this.walker.pathBuf;
```

2024-02-16 00:42 UTC, jdalton approved these changes
Pretty scoped debug, code comments, unit tests. What's not to like. Minor nit for extra expressiveness but I dig!

2024-02-16 12:12 UTC, Jarred-Sumner commented
Merging this so we can get it in the release

2024-02-16 12:12 UTC, merged

2024-02-16 12:36 UTC, leaumar commented
Thanks!