feat: More robust and faster shell escaping
oven-sh/bun pull request #8904
Opened 2024-02-14 21:37 UTC by zackradisic

### What does this PR do?

This makes shell escaping faster by changing the `escape()` and `needsEscape()` function to work with any string encoding (it previously would convert the string to UTF-8 and allocate it). The `needsEscape()` implementation for each string encoding is also SIMD-accelerated.

Also, instead of wrapping the string in quotes and adding backslashes to prevent the lexer from interpreting whitespace, quotes, etc. as special syntax, it passes the strings to the lexer to directly turn them into `Text` tokens.

This fixes makes the escaping logic more robust in situations like this:

```typescript
const str = "cookies & creme"
await $`echo "${str}"`
```

Which would before escape to this:
```typescript
await $`echo ""cookies & creme ""`
```

Which is obviously not correct

- [x] Code changes

### How did you verify your code works?

Zig files changed:
- [x] I checked the lifetime of memory allocated to verify it's (1) freed and (2) only freed when it should be
- [x] I included a test for the new code, or an existing test covers it
- [x] JSValue used outside outside of the stack is either wrapped in a JSC.Strong or is JSValueProtect'ed
- [x] I wrote TypeScript/JavaScript tests and they pass locally (`bun-debug test test-file-name.test`)

2024-02-14 22:17 UTC, paperdave requested changes
would like to see some very very minor touch ups. i also swear there was an issue open for something related to this but i couldn't find it. but great work

2024-02-14 22:17 UTC, paperdave commented on src/bun.js/api/BunObject.zig
> +    var stack_alloc = std.heap.stackFallback(@sizeOf(bun.String) * 4, arena.allocator());
i wonder if a helper function for this abstraction would be ncie
ive seen it a lot "please stack fallback for <n> items but it technically can be infinity so heap in that case"

2024-02-14 22:17 UTC, paperdave commented on src/shell/shell.zig
> +// const CodepointIterator = @import("../string_immutable.zig").CodepointIterator;
delete this line

2024-02-14 22:17 UTC, paperdave commented on src/shell/shell.zig
> +        return .{ .char = @intCast(this.cursor.c), .width = this.cursor.width };
what changed that needed this cast?

2024-02-14 22:17 UTC, paperdave commented on src/shell/shell.zig
> +                    defer str.deref();
you can use `String.static` here. it is identical to init with a string literal.

the defer deref is smart but in this case it doesn't really do anything interesting.

2024-02-14 22:17 UTC, paperdave commented on src/shell/shell.zig
> +                break :brk @intCast(str[i]);
u16 -> u32 does not need intcast

2024-02-15 05:00 UTC, Jarred-Sumner commented on src/shell/shell.zig
> +                            if (digit_buf_count >= 32) {
`digit_buf.len` should work btw

2024-02-16 05:13 UTC, zackradisic commented on src/shell/shell.zig
> +        return .{ .char = @intCast(this.cursor.c), .width = this.cursor.width };
It doesn't need to be cast, will remove

2024-02-16 12:09 UTC, merged