feat: add support --conditions flag
oven-sh/bun pull request #9106
Opened 2024-02-25 20:11 UTC by igorwessel

Closes https://github.com/oven-sh/bun/issues/8990

### What does this PR do?

This adds a new flag --conditions to bun run and build. When set, it will try to resolve custom conditions in package.json exports. Example:

In some NPM package have this package.json with a custom condition:

```json
{
  "name": "package",
  "exports": {
    "some-custom-condition": {
      "import": "./index.mjs",
      "require": "./index.cjs",
      "default": "./index.mjs"
    }
   "default": "./throw-error.mjs"
  }
}
```

We have this JS file importing our "package":
```js
import foo from 'package' // foo is a var with "Hello world!"

console.log(foo);
```

If we run it without passing the condition it should fall into the "throw-error.mjs" fallback because is the default, otherwise should resolves for ESM module or CJS module. Example:
```shell
bun --conditions some-custom-condition ./index.js

// prints "Hello world!"
```

The same behavior should happen in the bundle, resolving to the correct files according to the condition. Example:
```shell
bun build ./index.js --outfile ./build.js --conditions some-custom-condition
```

Our generate code should have the content for resolved custom condition export. Example for build
```js
// node_modules/package/index.js
var $foo = "Hello world!";

// src/index.js
console.log($foo);
```

- [x] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?

I wrote automated tests, and create a simple "package" to test the runtime and bundler behavior.

2024-02-25 22:22 UTC, igorwessel commented on src/api/schema.zig
I'm not sure here is the best way to set. I feel like this should be somewhere else related to the bundler options than the transform options. But I couldn't identify it.

2024-02-25 22:25 UTC, igorwessel commented on src/api/schema.zig
I'm unable to find a command to "auto-generated" for JS/TS related to schema. Does it have to make manually?

2024-02-27 09:02 UTC, paperdave commented on src/api/schema.zig
this "schema" thing is a holdover from very long ago when bun was just a wasm thing, not a full js runtime/package manager.

the code generator doesnt even work anymore, this is manually edited now.

2024-02-27 09:11 UTC, paperdave requested changes
nice to see this added. some notes that must be addressed:

2024-02-27 09:11 UTC, paperdave commented on src/options.zig
> +            opts.conditions.append(transform.conditions) catch unreachable;
```suggestion
            opts.conditions.append(transform.conditions) catch bun.outOfMemory();
```
i know we already do this but `unreachable` on a memory allocation is dangerous.

2024-02-27 09:11 UTC, paperclover commented on src/options.zig
> +            self.default.putAssumeCapacityNoClobber(condition, {});
this will crash if there are not enough items in the list.

use `try self.[list].ensureUnusedCapacity(customConditions.len);`

nit: zig's convention for variable names is snake case, though not followed everywhere. use `custom_conditions`. the variable could also just be called `conditions`

2024-02-27 09:11 UTC, paperclover commented on src/options.zig
> +    pub fn append(self: *ESMConditions, customConditions: []const string) !void {
can this be named appendSlice? to not be confused with zig std.ArrayList(T).append, which is a single item append.

2024-02-27 09:11 UTC, paperclover commented on src/cli.zig
> +        clap.parseParam("-c, --conditions <STR>...        Allow pass custom conditions to resolve.") catch unreachable,
i am uncertain on if `-c` should be an alias. not opinionated on this. maybe someone else is.

2024-02-27 21:42 UTC, igorwessel commented on src/cli.zig
> +        clap.parseParam("-c, --conditions <STR>...        Allow pass custom conditions to resolve.") catch unreachable,
I also had doubts but I chose to follow the Node API (https://nodejs.org/api/cli.html#-c-condition---conditionscondition), taking a look at esbuild they don't have aliases. (https://esbuild.github.io/api/#conditions)

2024-02-28 08:23 UTC, paperdave commented on src/cli.zig
> +        clap.parseParam("-c, --conditions <STR>...        Allow pass custom conditions to resolve.") catch unreachable,
thanks to jarred for pointing this out. we already have `-c`

<img width="939" alt="image" src="https://github.com/oven-sh/bun/assets/24465214/cdd1164c-f106-4ecb-91b9-1be165e280e0">

surprised your code compiled.

2024-02-28 08:31 UTC, paperdave requested changes
thanks for fixing the memory mistakes. one more review cycle.

- we should remove the `-c`, as there is already `-c` for config

- it would be nice to have more tests. to be clear i think your code is correct, this is just to prevent regressions.
  - passing two or more conditions (and the ordering of them is what is expected)
  - does it work in `bun build` (it should)

2024-02-28 22:31 UTC, igorwessel commented
> thanks for fixing the memory mistakes. one more review cycle.
> 
>     * we should remove the `-c`, as there is already `-c` for config
> 
>     * it would be nice to have more tests. to be clear i think your code is correct, this is just to prevent regressions.
>       
>       * passing two or more conditions (and the ordering of them is what is expected)
>       * does it work in `bun build` (it should)

Do you think there should be more testing for bundler? I saw that there was a test ported from esbuild, so I didn't think much about creating more cases. @paperdave

2024-02-28 22:36 UTC, paperdave approved these changes
i think it looks good

2024-03-01 13:53 UTC, gvilums requested changes
We can merge this once these grammar mistakes are fixed. Thanks for the contribution!

2024-03-01 13:53 UTC, gvilums commented on src/cli.zig
> +        clap.parseParam("--conditions <STR>...             Allow pass custom conditions to resolve.") catch unreachable,
```suggestion
        clap.parseParam("--conditions <STR>...             Pass custom conditions to resolve") catch unreachable,
```

2024-03-01 13:53 UTC, gvilums commented on src/cli.zig
> +        clap.parseParam("--conditions <STR>...            Allow pass custom conditions to resolve.") catch unreachable,
```suggestion
        clap.parseParam("--conditions <STR>...            Pass custom conditions to resolve") catch unreachable,
```

2024-03-01 15:40 UTC, igorwessel commented on src/cli.zig
> +        clap.parseParam("--conditions <STR>...             Allow pass custom conditions to resolve.") catch unreachable,
thanks!

2024-03-01 15:40 UTC, igorwessel commented on src/cli.zig
> +        clap.parseParam("--conditions <STR>...            Allow pass custom conditions to resolve.") catch unreachable,
thanks!

2024-03-01 18:08 UTC, gvilums approved these changes

2024-03-02 02:57 UTC, merged