Update sqlite.ts
oven-sh/bun pull request #9362
Opened 2024-03-11 17:29 UTC by R-Rajaneesh

➕ Added a `fileMustExist` in the database options

### What does this PR do?

This PR adds a check from `better-sqlite3` `fileMustExist` in the options of the constructor.
If `fileMustExist` is set to `true` then it'll not create a file on default else the file is created

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?
Needed review of this before doing tests.

2024-03-12 13:04 UTC, gvilums commented
Thank you for the PR. Do I understand correctly that this new option is the inverse of the `create` option? In that case I don't think we should implement it, as, in my opinion, the convenience of these redundant options is negated by the confusion they cause.

2024-03-12 15:39 UTC, R-Rajaneesh commented
> Thank you for the PR. Do I understand correctly that this new option is the inverse of the `create` option? In that case I don't think we should implement it, as, in my opinion, the convenience of these redundant options is negated by the confusion they cause.

@gvilums, Jarred and Dave told me to create an issue for this, since `better-sqlite3` has this options and **Bun** does not, even tho it says it implements all the feature in `better-sqlite3`. But I created a PR instead, and `create` was never an option in `better-sqlite3` in the first place.

2024-03-12 18:25 UTC, Electroid requested changes

2024-03-12 18:25 UTC, Electroid commented on src/js/bun/sqlite.ts
> +      }
```suggestion
      if(options.fileMustExist) {
        options.create = false;
      }
```

2024-03-12 18:55 UTC, Jarred-Sumner commented on src/js/bun/sqlite.ts
> +      }
```suggestion
      if(typeof options.fileMustExist === "boolean") {
          options.create = !options.fileMustExist;
      }
```

2024-03-12 21:49 UTC, paperdave commented on src/js/bun/sqlite.ts
> +      }
this likely fixes the test failure

2024-07-10 01:40 UTC, Jarred-Sumner commented
Closing due to lack of tests

2024-07-10 01:40 UTC, closed without merging