Add PowerShell completions
oven-sh/bun pull request #9441
Opened 2024-03-15 16:44 UTC by sequencerr

### What does this PR do?

Closes: https://github.com/oven-sh/bun/issues/8939

- [ ] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [ ] Code changes

### How did you verify your code works?

2024-03-15 16:45 UTC, paperdave commented
have not read through in depth but this looks legendary

2024-03-15 16:48 UTC, sequencerr commented
<3 thanks. there are still some todos, link unlink completions, replace `get bins` with `bun.exe get competes [a-z]` (most are crashing on win). and zig part is pseudocoded

2024-03-15 18:20 UTC, sequencerr commented on completions/bun.ps1
> +Microsoft.PowerShell.Core\Register-ArgumentCompleter -CommandName bun -Native -ScriptBlock $_bun_register_completer
It's possible to define `bun, bun.exe` at once. Do we need this?

2024-04-16 02:29 UTC, paperdave requested changes
I think the approach for this should deviate from what was taken for bash, zsh, and fish. See [this comment](https://github.com/oven-sh/bun/issues/8939#issuecomment-2033044246) in the powershell completions issue.

Instead of a 1.1k line addition to the user's powershell startup profile, this would be better done as a part of `bun getcompletes` and uses what bcdev-com suggests in [this comment](https://github.com/oven-sh/bun/issues/8939#issuecomment-2040644434)

2024-04-20 17:55 UTC, closed without merging