feat: Implemented some jest extended methods
oven-sh/bun pull request #9741
Opened 2024-03-30 11:05 UTC by nithinkjoy-tech

### What does this PR do?

Add `toContainAllKeys` `toContainValue` `toContainValues` `toContainAllValues` `toContainAnyValues` from #1825 

- [X] Documentation or TypeScript types (it's okay to leave the rest blank in this case)
- [X] Code changes

### How did you verify your code works?

- [X] Wrote automated test cases
- [X] I included a test for the new code, or an existing test covers it
- [X] I wrote TypeScript/JavaScript tests and they pass locally (`bun-debug test test-file-name.test`)

2024-04-04 04:38 UTC, Electroid commented
Thanks for working on this PR! We'll take a look at it soon, we're currently busy getting fixes for Windows in Bun v1.1.1.

2024-06-01 09:52 UTC, Jarred-Sumner commented
@dylan-conway can you take a look and review?

2024-06-07 21:12 UTC, dylan-conway commented on src/bun.js/bindings/bindings.zig
> +    pub fn getKeys(_: JSValue, globalThis: *JSGlobalObject, value: JSC.JSValue) JSValue {
instead of `getKeys`, I would use `keys()` and change the signature to look like: `pub fn keys(value: JSValue, globalThis: *JSGlobalObject) JSValue`

2024-06-07 21:13 UTC, dylan-conway commented on src/bun.js/bindings/headers.zig
> +pub extern fn JSC__JSValue__makeWithNameAndPrototype(arg0: *bindings.JSGlobalObject, arg1: ?*anyopaque, arg2: ?*anyopaque, arg3: [*c]const ZigString) JSC__JSValue;
this `JSC__JSValue__makeWithNameAndPrototype` can be deleted

2024-06-07 21:13 UTC, dylan-conway commented on src/bun.js/bindings/headers.h
> +CPP_DECL JSC__JSValue JSC__JSValue__makeWithNameAndPrototype(JSC__JSGlobalObject* arg0, void* arg1, void* arg2, const ZigString* arg3);
```suggestion

```

2024-06-07 21:45 UTC, dylan-conway commented on src/bun.js/bindings/bindings.cpp
> +JSC__JSValue JSC__JSValue__values(JSC__JSGlobalObject* globalObject, JSC__JSValue objectValue)
I like that this is the exact implementation of `Object.values`, but we shouldn't have duplicated code from JSC that can get out of sync. For now this is good enough, but in the future we will need to modify `ObjectConstructor.cpp/h` to expose the implementation of `Object.values`, similar to what is done for `Object.freeze/seal`

2024-06-07 22:00 UTC, dylan-conway commented on src/bun.js/test/expect.zig
> +        expected.ensureStillAlive();
An error should be thrown if `expected` is not an array. jest-extended does not do this, but an error will be thrown shortly after when they call `expected.every()`

2024-06-07 22:03 UTC, dylan-conway commented on src/bun.js/test/expect.zig
> +        const expected = arguments[0];
Same here, an error should be thrown if `expected` isn't an array

2024-06-07 22:05 UTC, dylan-conway commented on src/bun.js/test/expect.zig
> +        const expected = arguments[0];
Same array check here

2024-06-07 22:06 UTC, dylan-conway commented on src/bun.js/test/expect.zig
> +        const expected_line = "Expected to contain: <green>{any}<r>\n";
```suggestion
        const expected_line = "Expected to contain all values: <green>{any}<r>\n";
```

2024-06-07 22:08 UTC, dylan-conway commented on src/bun.js/test/expect.zig
> +            const expected_line = "Expected to not contain: <green>{any}<r>\nReceived: <red>{any}<r>\n";
```suggestion
            const expected_line = "Expected to not contain all values: <green>{any}<r>\nReceived: <red>{any}<r>\n";
```

2024-06-07 22:08 UTC, dylan-conway commented on src/bun.js/test/expect.zig
> +        const expected_line = "Expected to contain: <green>{any}<r>\n";
```suggestion
        const expected_line = "Expected to contain any of the following values: <green>{any}<r>\n";
```

2024-06-07 22:08 UTC, dylan-conway commented on src/bun.js/test/expect.zig
> +            const expected_line = "Expected to not contain: <green>{any}<r>\nReceived: <red>{any}<r>\n";
```suggestion
            const expected_line = "Expected to not contain any of the following values: <green>{any}<r>\nReceived: <red>{any}<r>\n";
```

2024-06-07 22:11 UTC, dylan-conway commented on src/bun.js/test/expect.zig
> +        var iter_value = value.getKeys(globalObject, value);
Commented in `bindings.zig`, this would become `value.keys(globalObject)`

2024-06-07 22:12 UTC, dylan-conway requested changes
Sorry review took so long. I think overall this is good. I left a few comments for changes to error messages and checking if `expected` is an array

2024-06-08 10:35 UTC, nithinkjoy-tech commented
@dylan-conway  Thank you for taking the time to review my code! I have updated the code based on your feedback. Can you please have a look.

2024-06-09 03:59 UTC, dylan-conway approved these changes
Thanks!

2024-06-09 03:59 UTC, merged